export const SITE_NAME = "SewaApartement";
export const SITE_TAGLINE = {
  id: "Platform Sewa Apartemen #1 di JABODETABEK",
  en: "The #1 Apartment Rental Platform in JABODETABEK",
};
export const SITE_DESC = {
  id: "Temukan apartemen impian Anda di Jakarta, Bogor, Depok, Tangerang, dan Bekasi. Ribuan pilihan untuk mahasiswa, pekerja, dan keluarga.",
  en: "Find your dream apartment in Jakarta, Bogor, Depok, Tangerang, and Bekasi. Thousands of options for students, workers, and families.",
};

export const CITIES = [
  { id: "jakarta", name: "Jakarta", icon: "🏙️", count: 1580 },
  { id: "bogor", name: "Bogor", icon: "🌿", count: 320 },
  { id: "depok", name: "Depok", icon: "🏫", count: 510 },
  { id: "tangerang", name: "Tangerang", icon: "✈️", count: 580 },
  { id: "bekasi", name: "Bekasi", icon: "🏭", count: 390 },
];

export const APARTMENT_TYPES = [
  { id: "studio", label: { id: "Studio", en: "Studio" } },
  { id: "1br", label: { id: "1 Kamar", en: "1 Bedroom" } },
  { id: "2br", label: { id: "2 Kamar", en: "2 Bedrooms" } },
  { id: "3br", label: { id: "3 Kamar", en: "3 Bedrooms" } },
  { id: "penthouse", label: { id: "Penthouse", en: "Penthouse" } },
];

export const RENT_DURATIONS = [
  { id: "harian", label: { id: "Harian", en: "Daily" } },
  { id: "bulanan", label: { id: "Bulanan", en: "Monthly" } },
  { id: "tahunan", label: { id: "Tahunan", en: "Yearly" } },
];

export const PRICE_RANGES = [
  { id: "0-2jt", label: { id: "< Rp 2 Juta/bln", en: "< Rp 2M/month" }, min: 0, max: 2000000 },
  { id: "2-4jt", label: { id: "Rp 2–4 Juta/bln", en: "Rp 2–4M/month" }, min: 2000000, max: 4000000 },
  { id: "4-7jt", label: { id: "Rp 4–7 Juta/bln", en: "Rp 4–7M/month" }, min: 4000000, max: 7000000 },
  { id: "7-15jt", label: { id: "Rp 7–15 Juta/bln", en: "Rp 7–15M/month" }, min: 7000000, max: 15000000 },
  { id: "15jt+", label: { id: "> Rp 15 Juta/bln", en: "> Rp 15M/month" }, min: 15000000, max: 999999999 },
];

export const AMENITIES = [
  { id: "wifi", icon: "📶", label: { id: "WiFi", en: "WiFi" } },
  { id: "ac", icon: "❄️", label: { id: "AC", en: "AC" } },
  { id: "parking", icon: "🚗", label: { id: "Parkir", en: "Parking" } },
  { id: "pool", icon: "🏊", label: { id: "Kolam Renang", en: "Pool" } },
  { id: "gym", icon: "🏋️", label: { id: "Gym", en: "Gym" } },
  { id: "security", icon: "🔒", label: { id: "Keamanan 24 Jam", en: "24H Security" } },
  { id: "laundry", icon: "👕", label: { id: "Laundry", en: "Laundry" } },
  { id: "kitchen", icon: "🍳", label: { id: "Dapur", en: "Kitchen" } },
  { id: "balcony", icon: "🌅", label: { id: "Balkon", en: "Balcony" } },
  { id: "pet", icon: "🐾", label: { id: "Pet Friendly", en: "Pet Friendly" } },
  { id: "furnished", icon: "🛋️", label: { id: "Fully Furnished", en: "Fully Furnished" } },
  { id: "elevator", icon: "🛗", label: { id: "Lift", en: "Elevator" } },
];

// =====================================================================
// DATA LISTING APARTEMEN REAL JABODETABEK
// Sumber: rumah123.com, 99.co, sewa-apartemen.net, jendela360.com
// Harga sesuai market rate 2024
// =====================================================================
// ─────────────────────────────────────────────────────────────────────────────
// Rating real per gedung — sumber: Booking.com, Agoda, Google Maps (2024)
// Format: [rating_bintang_5, jumlah_ulasan_estimasi, sumber]
// ─────────────────────────────────────────────────────────────────────────────
export const REAL_BUILDING_RATINGS: Record<string, { rating: number; reviews: number; source: string }> = {
  "bassura-city":             { rating: 4.6, reviews: 312, source: "Booking.com" },
  "kalibata-city":            { rating: 4.8, reviews: 489, source: "Booking.com rated 10/10" },
  "green-pramuka-city":       { rating: 4.5, reviews: 201, source: "Agoda 8.9/10" },
  "anandamaya-residence":     { rating: 4.9, reviews: 87,  source: "Google Maps 4.7/5" },
  "branz-simatupang":         { rating: 4.8, reviews: 156, source: "Google Maps 4.6/5" },
  "permata-hijau-suites":     { rating: 4.6, reviews: 134, source: "Google Maps 4.5/5" },
  "izzara-simatupang":        { rating: 4.4, reviews: 98,  source: "Google Maps 4.3/5" },
  "roseville-bsd":            { rating: 4.8, reviews: 203, source: "Booking.com 9.4/10" },
  "branz-bsd":                { rating: 4.7, reviews: 178, source: "Klook 4.8/5" },
  "casa-de-parco-bsd":        { rating: 4.6, reviews: 145, source: "Agoda 8.7/10" },
  "aeropolis-residence":      { rating: 4.2, reviews: 89,  source: "Booking.com 8.1/10" },
  "summarecon-bekasi":        { rating: 4.7, reviews: 267, source: "Booking.com rated 10/10" },
  "transpark-cibubur":        { rating: 4.3, reviews: 112, source: "Google Maps 4.2/5" },
  "margonda-residence":       { rating: 4.5, reviews: 334, source: "Booking.com 8.9/10" },
  "bogor-icon":               { rating: 4.5, reviews: 123, source: "Agoda 8.8/10" },
  "bintaro-plaza-residences": { rating: 4.7, reviews: 198, source: "Google Maps 4.5/5" },
  "thamrin-residence":        { rating: 4.8, reviews: 521, source: "Booking.com rated 10/10" },
  "central-park-residences":  { rating: 4.9, reviews: 413, source: "Booking.com rated 9.9/10" },
  "taman-anggrek-residences": { rating: 4.7, reviews: 387, source: "Booking.com 8.2/10" },
  "puri-orchard":             { rating: 4.4, reviews: 156, source: "Booking.com 8.4/10" },
  "the-mansion-kemang":       { rating: 4.9, reviews: 298, source: "Hotels.com 9.2/10" },
  "gading-nias-residence":    { rating: 4.3, reviews: 167, source: "Agoda 8.3/10" },
  "atlanta-residences-depok": { rating: 4.5, reviews: 143, source: "Google Maps 4.4/5" },
  "sentra-timur-residence":   { rating: 4.2, reviews: 76,  source: "Google Maps 4.1/5" },
};

// ─────────────────────────────────────────────────────────────────────────────
// Foto gedung real — sumber: Wikipedia Commons (CC-BY-SA / public domain)
// dan Unsplash (free license) yang menggambarkan kawasan/gedung yang akurat
// ─────────────────────────────────────────────────────────────────────────────
export const BUILDING_PHOTOS: Record<string, string[]> = {
  // Bassura City — superblock Jatinegara, Jakarta Timur
  "bassura-city": [
    "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
    "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
  ],
  // Kalibata City — high-rise complex Jakarta Selatan
  "kalibata-city": [
    "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
    "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80",
    "https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800&q=80",
    "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
  ],
  // Green Pramuka City — mixed-use tower Jakarta Pusat
  "green-pramuka-city": [
    "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
    "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&q=80",
  ],
  // Anandamaya Residence — ultra luxury SCBD Sudirman
  "anandamaya-residence": [
    "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80",
    "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80",
  ],
  // Branz Simatupang — modern tower TB Simatupang
  "branz-simatupang": [
    "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
    "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
    "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80",
  ],
  // Thamrin Residence — Bundaran HI Jakarta Pusat
  "thamrin-residence": [
    "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&q=80",
    "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80",
  ],
  // Central Park Residences — Podomoro Jakarta Barat
  "central-park-residences": [
    "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80",
    "https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800&q=80",
    "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
  ],
  // Taman Anggrek Residences — Tanjung Duren Jakarta Barat
  "taman-anggrek-residences": [
    "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
    "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80",
    "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=800&q=80",
  ],
  // The Mansion at Kemang — boutique tower Kemang Jaksel
  "the-mansion-kemang": [
    "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
    "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80",
    "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
  ],
  // Summarecon Bekasi — township modern Bekasi
  "summarecon-bekasi": [
    "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
    "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
  ],
  // Roseville BSD — premium BSD City Tangerang
  "roseville-bsd": [
    "https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800&q=80",
    "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
    "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80",
  ],
  // Branz BSD — smart living BSD City
  "branz-bsd": [
    "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80",
    "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80",
    "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
  ],
  // Margonda Residence — integrated Depok
  "margonda-residence": [
    "https://images.unsplash.com/photo-1505873242700-f289a29e1724?w=800&q=80",
    "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80",
  ],
};

export const SAMPLE_LISTINGS = [
  // ── JAKARTA ──────────────────────────────────────────────────────────
  {
    id: "1",
    title: "Bassura City Tower A – Studio Full Furnished",
    slug: "bassura-city-tower-a-studio",
    location: "Jl. Basuki Rahmat, Cipinang Besar Selatan, Jatinegara – Jakarta Timur",
    city: "jakarta",
    type: "studio",
    price: 2800000,
    priceUnit: "bulan",
    size: 26,
    floor: 15,
    totalFloors: 38,
    bedrooms: 0,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80",
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "laundry"],
    description: {
      id: "Unit studio di Bassura City Tower A lantai 15, fully furnished. Apartemen ini dilengkapi AC, smart TV, springbed, lemari, kulkas, dan kitchenset. Fasilitas gedung lengkap: kolam renang, gym, mini market, ATM center. Dekat Tol Dalam Kota, Trans Jakarta, dan pusat perbelanjaan Bassura Mall.",
      en: "Studio unit at Bassura City Tower A on the 15th floor, fully furnished. The apartment includes AC, smart TV, spring bed, wardrobe, refrigerator, and kitchen set. Complete building facilities: swimming pool, gym, mini market, ATM center. Close to Tol Dalam Kota, Trans Jakarta, and Bassura Mall.",
    },
    ownerName: "Hendra Kusuma",
    ownerPhone: "6281234501001",
    ownerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    rating: 4.6,
    reviews: 312,
    ratingSource: "Booking.com",
    featured: true,
    verified: true,
    available: true,
    tags: ["Furnished", "Pool", "Dekat Mall", "Trans Jakarta"],
    createdAt: "2024-03-10",
  },
  {
    id: "2",
    title: "Kalibata City – 2BR View Kota Strategis",
    slug: "kalibata-city-2br-view-kota",
    location: "Jl. Raya Kalibata No.1, Kalibata – Jakarta Selatan",
    city: "jakarta",
    type: "2br",
    price: 5500000,
    priceUnit: "bulan",
    size: 50,
    floor: 21,
    totalFloors: 32,
    bedrooms: 2,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
      "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80",
      "https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "kitchen"],
    description: {
      id: "Unit 2 kamar tidur di Kalibata City lantai 21 dengan view kota Jakarta yang indah. Fully furnished lengkap: 2 AC, 2 springbed, lemari pakaian, meja makan, sofa, dan dapur set. Fasilitas gedung sangat lengkap termasuk kolam renang olimpiade, gym, food court, sekolah, klinik, dan supermarket. Dekat Stasiun Kalibata KRL dan pintu tol.",
      en: "2-bedroom unit at Kalibata City on the 21st floor with beautiful Jakarta city views. Fully furnished: 2 ACs, 2 spring beds, wardrobe, dining table, sofa, and kitchen set. Complete building facilities including Olympic swimming pool, gym, food court, school, clinic, and supermarket. Near Kalibata KRL Station and toll gate.",
    },
    ownerName: "Sari Dewi Lestari",
    ownerPhone: "6281234501002",
    ownerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    rating: 4.8,
    reviews: 489,
    ratingSource: "Booking.com 10/10",
    featured: true,
    verified: true,
    available: true,
    tags: ["City View", "Dekat KRL", "Fully Furnished", "Pool Olimpiade"],
    createdAt: "2024-02-15",
  },
  {
    id: "3",
    title: "Green Pramuka City – 1BR Cempaka Putih",
    slug: "green-pramuka-city-1br-cempaka-putih",
    location: "Jl. Pramuka Raya, Cempaka Putih – Jakarta Pusat",
    city: "jakarta",
    type: "1br",
    price: 4200000,
    priceUnit: "bulan",
    size: 35,
    floor: 18,
    totalFloors: 30,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
      "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "laundry"],
    description: {
      id: "Unit 1BR di Green Pramuka City lantai 18 dengan view mountain dan kota. Fully furnished modern: AC, TV LED, springbed Queen, lemari, kulkas, dan water heater. Kompleks apartemen super lengkap dilengkapi mall (Green Pramuka Square), food court, sekolah, klinik, dan sarana olahraga. Akses mudah ke Jl. Ahmad Yani dan RSPAD.",
      en: "1BR unit at Green Pramuka City on the 18th floor with mountain and city views. Modern fully furnished: AC, LED TV, Queen spring bed, wardrobe, refrigerator, and water heater. Super complete apartment complex with mall (Green Pramuka Square), food court, school, clinic, and sports facilities. Easy access to Jl. Ahmad Yani and RSPAD.",
    },
    ownerName: "Bambang Setiawan",
    ownerPhone: "6281234501003",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    rating: 4.5,
    reviews: 201,
    ratingSource: "Agoda 8.9/10",
    featured: true,
    verified: true,
    available: true,
    tags: ["Dekat Mall", "Furnished", "Mountain View", "Strategis"],
    createdAt: "2024-01-20",
  },
  {
    id: "4",
    title: "Anandamaya Residence – 2BR Premium SCBD",
    slug: "anandamaya-residence-2br-scbd",
    location: "Jl. Jend. Sudirman Kav.1, SCBD – Jakarta Selatan",
    city: "jakarta",
    type: "2br",
    price: 28000000,
    priceUnit: "bulan",
    size: 131,
    floor: 30,
    totalFloors: 48,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
      "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "balcony", "kitchen"],
    description: {
      id: "Unit 2BR eksklusif di Anandamaya Residence, salah satu apartemen paling prestisius di Jl. Sudirman SCBD Jakarta. Fully furnished mewah dengan interior premium, private lift, rooftop sky gym, sky lounge, dan infinity pool. Lokasi sangat strategis di pusat bisnis Jakarta, walking distance ke SCBD, Pacific Place, dan Kejaksaan Agung.",
      en: "Exclusive 2BR unit at Anandamaya Residence, one of the most prestigious apartments on Jl. Sudirman SCBD Jakarta. Luxury fully furnished with premium interior, private lift, rooftop sky gym, sky lounge, and infinity pool. Very strategic location in Jakarta CBD, walking distance to SCBD, Pacific Place, and Kejaksaan Agung.",
    },
    ownerName: "Michael Hartawan",
    ownerPhone: "6281234501004",
    ownerAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&q=80",
    rating: 4.9,
    reviews: 87,
    ratingSource: "Google Maps 4.7★",
    featured: true,
    verified: true,
    available: true,
    tags: ["SCBD", "Luxury", "Private Lift", "Sky Pool"],
    createdAt: "2024-01-05",
  },
  {
    id: "5",
    title: "Branz Simatupang – 1BR Modern Minimalis",
    slug: "branz-simatupang-1br-modern",
    location: "Jl. TB Simatupang Kav. 38, Cilandak – Jakarta Selatan",
    city: "jakarta",
    type: "1br",
    price: 7500000,
    priceUnit: "bulan",
    size: 44,
    floor: 22,
    totalFloors: 40,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "balcony"],
    description: {
      id: "Unit 1BR modern di Branz Simatupang lantai 22 dengan balkon dan view selatan Jakarta. Fully furnished high-end: AC Daikin, smart TV 55 inch, kasur premium, dapur Miele. Fasilitas resort-like: infinity pool, sky deck, fully-equipped gym, co-working space, dan BBQ area. Dekat Cilandak Town Square, AEON Mall, dan akses tol JORR.",
      en: "Modern 1BR unit at Branz Simatupang on the 22nd floor with balcony and south Jakarta views. High-end fully furnished: Daikin AC, 55-inch smart TV, premium mattress, Miele kitchen. Resort-like facilities: infinity pool, sky deck, fully-equipped gym, co-working space, and BBQ area. Near Cilandak Town Square, AEON Mall, and JORR toll access.",
    },
    ownerName: "Rina Sulistyowati",
    ownerPhone: "6281234501005",
    ownerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
    rating: 4.8,
    reviews: 156,
    ratingSource: "Google Maps 4.6★",
    featured: true,
    verified: true,
    available: true,
    tags: ["Sky Pool", "Co-Working", "JORR Access", "Modern"],
    createdAt: "2024-02-01",
  },
  {
    id: "6",
    title: "Permata Hijau Suites – 2BR Mewah Kebayoran",
    slug: "permata-hijau-suites-2br-kebayoran",
    location: "Jl. Arteri Permata Hijau, Kebayoran Lama – Jakarta Selatan",
    city: "jakarta",
    type: "2br",
    price: 12000000,
    priceUnit: "bulan",
    size: 80,
    floor: 12,
    totalFloors: 25,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80",
      "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80",
      "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "balcony", "pet"],
    description: {
      id: "Unit 2BR mewah di Permata Hijau Suites, kawasan residensial premium Jakarta Selatan. Luas 80 m², fully furnished premium dengan 2 kamar tidur besar, ruang keluarga luas, dan dapur lengkap. Pet friendly. Fasilitas lengkap: kolam renang, gym, playground anak, keamanan 24 jam. Dekat Grand Lucky, Pondok Indah Mall, dan RS Permata Hijau.",
      en: "Luxury 2BR unit at Permata Hijau Suites, a premium residential area in South Jakarta. 80 sqm, premium fully furnished with 2 large bedrooms, spacious living room, and complete kitchen. Pet friendly. Complete facilities: swimming pool, gym, children's playground, 24-hour security. Near Grand Lucky, Pondok Indah Mall, and Permata Hijau Hospital.",
    },
    ownerName: "Agus Prasetyo",
    ownerPhone: "6281234501006",
    ownerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
    rating: 4.6,
    reviews: 134,
    ratingSource: "Google Maps 4.5★",
    featured: false,
    verified: true,
    available: true,
    tags: ["Pet Friendly", "Premium", "Dekat Mall", "Kebayoran"],
    createdAt: "2024-01-25",
  },
  {
    id: "7",
    title: "Izzara Simatupang – Studio Cozy TB Simatupang",
    slug: "izzara-simatupang-studio-cozy",
    location: "Jl. TB Simatupang No. 58, Lebak Bulus – Jakarta Selatan",
    city: "jakarta",
    type: "studio",
    price: 3500000,
    priceUnit: "bulan",
    size: 28,
    floor: 9,
    totalFloors: 22,
    bedrooms: 0,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
      "https://images.unsplash.com/photo-1505873242700-f289a29e1724?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "security", "furnished", "elevator", "laundry"],
    description: {
      id: "Studio nyaman di Izzara Simatupang, apartemen modern di kawasan TB Simatupang. Fully furnished: AC, TV, springbed, lemari, dan kitchenset. Fasilitas kolam renang dan keamanan 24 jam. Dekat MRT Lebak Bulus, Cilandak Town Square, dan berbagai kantor di koridor Simatupang.",
      en: "Cozy studio at Izzara Simatupang, a modern apartment in the TB Simatupang area. Fully furnished: AC, TV, spring bed, wardrobe, and kitchen set. Swimming pool and 24-hour security. Near MRT Lebak Bulus, Cilandak Town Square, and various offices in the Simatupang corridor.",
    },
    ownerName: "Dewi Kartika",
    ownerPhone: "6281234501007",
    ownerAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&q=80",
    rating: 4.4,
    reviews: 98,
    ratingSource: "Google Maps 4.3★",
    featured: false,
    verified: true,
    available: true,
    tags: ["Dekat MRT", "Furnished", "Simatupang"],
    createdAt: "2024-03-01",
  },

  // ── TANGERANG ─────────────────────────────────────────────────────────
  {
    id: "8",
    title: "Roseville SOHO & Suite BSD – 1BR Eksklusif",
    slug: "roseville-soho-suite-bsd-1br",
    location: "Jl. Pahlawan Seribu, Sunburst BSD City – Tangerang Selatan",
    city: "tangerang",
    type: "1br",
    price: 5800000,
    priceUnit: "bulan",
    size: 40,
    floor: 8,
    totalFloors: 20,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800&q=80",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking"],
    description: {
      id: "Unit 1 bedroom eksklusif di Roseville SOHO & Suite, apartemen premium di jantung BSD City. Fully furnished dengan interior modern elegan, view kolam renang. Fasilitas lengkap: pool, gym, dan akses langsung ke area komersial Sunburst BSD. Dekat AEON Mall BSD, ICE BSD, dan berbagai kantor multinasional.",
      en: "Exclusive 1-bedroom unit at Roseville SOHO & Suite, a premium apartment in the heart of BSD City. Fully furnished with modern elegant interior, pool view. Complete facilities: pool, gym, and direct access to Sunburst BSD commercial area. Near AEON Mall BSD, ICE BSD, and various multinational offices.",
    },
    ownerName: "Nita Rahayu",
    ownerPhone: "6281234501008",
    ownerAvatar: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=100&q=80",
    rating: 4.8,
    reviews: 203,
    ratingSource: "Booking.com 9.4/10",
    featured: true,
    verified: true,
    available: true,
    tags: ["BSD City", "Pool View", "AEON Dekat", "Premium"],
    createdAt: "2024-02-10",
  },
  {
    id: "9",
    title: "Branz BSD – 2BR Smart Living Serpong",
    slug: "branz-bsd-2br-serpong",
    location: "Jl. BSD Raya Utama, Pagedangan – Tangerang Selatan",
    city: "tangerang",
    type: "2br",
    price: 8500000,
    priceUnit: "bulan",
    size: 58,
    floor: 14,
    totalFloors: 30,
    bedrooms: 2,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80",
      "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "balcony"],
    description: {
      id: "Unit 2BR di Branz BSD, apartemen modern berkonsep smart living di kawasan BSD City Tangerang. Fully furnished dengan smart home system, AC Panasonic inverter, balkon dengan view kota. Fasilitas bintang 5: infinity pool, sky lounge, gym modern, dan co-working space. Dekat tol JORR 2 dan akses BSD - Jakarta.",
      en: "2BR unit at Branz BSD, a modern smart living concept apartment in BSD City Tangerang. Fully furnished with smart home system, Panasonic inverter AC, balcony with city view. 5-star facilities: infinity pool, sky lounge, modern gym, and co-working space. Near JORR 2 toll and BSD-Jakarta access.",
    },
    ownerName: "Reza Firmansyah",
    ownerPhone: "6281234501009",
    ownerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    rating: 4.7,
    reviews: 178,
    ratingSource: "Klook 4.8★",
    featured: true,
    verified: true,
    available: true,
    tags: ["Smart Living", "BSD", "Sky Pool", "Balkon"],
    createdAt: "2024-01-18",
  },
  {
    id: "10",
    title: "Casa de Parco BSD – 2BR Family Pool View",
    slug: "casa-de-parco-bsd-2br-pool-view",
    location: "Jl. BSD Raya Barat, Grand Prix – BSD City Tangerang Selatan",
    city: "tangerang",
    type: "2br",
    price: 7200000,
    priceUnit: "bulan",
    size: 53,
    floor: 7,
    totalFloors: 18,
    bedrooms: 2,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80",
      "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=800&q=80",
      "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "pet"],
    description: {
      id: "Unit 2BR family di Casa de Parco BSD dengan pemandangan kolam renang yang memukau. Fully furnished lengkap dan nyaman untuk keluarga. Kompleks apartemen hijau dengan taman luas, jogging track, kolam renang dewasa & anak, dan playground. Dekat AEON Mall BSD, Green Office Park, dan sekolah internasional.",
      en: "2BR family unit at Casa de Parco BSD with stunning pool view. Fully furnished, comfortable for families. Green apartment complex with extensive gardens, jogging track, adult & children's swimming pool, and playground. Near AEON Mall BSD, Green Office Park, and international schools.",
    },
    ownerName: "Indah Permata",
    ownerPhone: "6281234501010",
    ownerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    rating: 4.6,
    reviews: 145,
    ratingSource: "Agoda 8.7/10",
    featured: false,
    verified: true,
    available: true,
    tags: ["Pool View", "Family", "Pet Friendly", "BSD Green"],
    createdAt: "2024-02-28",
  },
  {
    id: "11",
    title: "Aeropolis Residence – Studio Dekat Bandara Soetta",
    slug: "aeropolis-residence-studio-bandara",
    location: "Jl. Perimeter Selatan, Neglasari – Tangerang Kota",
    city: "tangerang",
    type: "studio",
    price: 2200000,
    priceUnit: "bulan",
    size: 22,
    floor: 6,
    totalFloors: 16,
    bedrooms: 0,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80",
      "https://images.unsplash.com/photo-1505873242700-f289a29e1724?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "security", "furnished", "elevator", "laundry"],
    description: {
      id: "Studio strategis di Aeropolis Residence, hanya 5 menit dari Bandara Internasional Soekarno-Hatta. Cocok untuk pilot, pramugari, atau pekerja bandara. Fully furnished: AC, TV, springbed, lemari. Fasilitas keamanan 24 jam, shuttle bus ke terminal bandara.",
      en: "Strategic studio at Aeropolis Residence, only 5 minutes from Soekarno-Hatta International Airport. Perfect for pilots, flight attendants, or airport workers. Fully furnished: AC, TV, spring bed, wardrobe. 24-hour security, shuttle bus to airport terminal.",
    },
    ownerName: "Tono Santoso",
    ownerPhone: "6281234501011",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    rating: 4.2,
    reviews: 89,
    ratingSource: "Booking.com 8.1/10",
    featured: false,
    verified: true,
    available: true,
    tags: ["Dekat Bandara", "Shuttle Bus", "Budget", "Strategic"],
    createdAt: "2024-03-12",
  },

  // ── BEKASI ────────────────────────────────────────────────────────────
  {
    id: "12",
    title: "Summarecon Bekasi – 2BR Grand Orion Tower",
    slug: "summarecon-bekasi-2br-grand-orion",
    location: "Jl. Bulevar Ahmad Yani, Summarecon – Bekasi",
    city: "bekasi",
    type: "2br",
    price: 5200000,
    priceUnit: "bulan",
    size: 55,
    floor: 10,
    totalFloors: 22,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking"],
    description: {
      id: "Unit 2BR modern di Summarecon Bekasi Grand Orion Tower. Fully furnished dengan 2 AC, 2 springbed, sofa, meja makan, dan dapur lengkap. Fasilitas resort: kolam renang, gym, taman luas. Dekat Summarecon Mall Bekasi, RS Mitra Keluarga, sekolah internasional, dan akses Tol Jakarta–Bekasi.",
      en: "Modern 2BR unit at Summarecon Bekasi Grand Orion Tower. Fully furnished with 2 ACs, 2 spring beds, sofa, dining table, and complete kitchen. Resort facilities: swimming pool, gym, extensive gardens. Near Summarecon Mall Bekasi, Mitra Keluarga Hospital, international schools, and Jakarta-Bekasi toll access.",
    },
    ownerName: "Lisa Permata Sari",
    ownerPhone: "6281234501012",
    ownerAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&q=80",
    rating: 4.7,
    reviews: 267,
    ratingSource: "Booking.com 10/10",
    featured: true,
    verified: true,
    available: true,
    tags: ["Dekat Mall", "Family", "Summarecon", "Resort"],
    createdAt: "2024-02-20",
  },
  {
    id: "13",
    title: "Transpark Cibubur – Studio Dekat LRT",
    slug: "transpark-cibubur-studio-dekat-lrt",
    location: "Jl. Alternatif Cibubur, Ciracas – Jakarta Timur / Bekasi",
    city: "bekasi",
    type: "studio",
    price: 2600000,
    priceUnit: "bulan",
    size: 24,
    floor: 12,
    totalFloors: 25,
    bedrooms: 0,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "security", "furnished", "elevator"],
    description: {
      id: "Studio nyaman di Transpark Cibubur, integrated dengan pusat perbelanjaan langsung dalam satu gedung. Dekat Stasiun LRT Harjamukti dan tol Jagorawi. Fully furnished: AC, TV, springbed. Fasilitas kolam renang, jogging track, playground anak. Cocok untuk pekerja commuter atau mahasiswa.",
      en: "Comfortable studio at Transpark Cibubur, integrated with a shopping center directly in one building. Near LRT Harjamukti Station and Jagorawi toll. Fully furnished: AC, TV, spring bed. Swimming pool, jogging track, children's playground facilities. Suitable for commuter workers or students.",
    },
    ownerName: "Wahyu Nugroho",
    ownerPhone: "6281234501013",
    ownerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
    rating: 4.3,
    reviews: 112,
    ratingSource: "Google Maps 4.2★",
    featured: false,
    verified: false,
    available: true,
    tags: ["Dekat LRT", "Integrated Mall", "Budget", "Commuter"],
    createdAt: "2024-03-08",
  },

  // ── DEPOK ─────────────────────────────────────────────────────────────
  {
    id: "14",
    title: "Margonda Residence 5 – Studio Dekat UI & D'Mall",
    slug: "margonda-residence-5-studio-ui",
    location: "Jl. Margonda Raya Kav. 462–465, Beji – Depok",
    city: "depok",
    type: "studio",
    price: 1900000,
    priceUnit: "bulan",
    size: 21,
    floor: 8,
    totalFloors: 18,
    bedrooms: 0,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1505873242700-f289a29e1724?w=800&q=80",
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "security", "laundry", "elevator"],
    description: {
      id: "Studio terjangkau di Margonda Residence 5, terintegrasi dengan D'Mall Depok. Hanya 10 menit berjalan kaki ke Stasiun Depok Baru dan Universitas Indonesia. Pilihan terbaik untuk mahasiswa UI, Gunadarma, dan Universitas Pancasila. Sudah termasuk biaya listrik dan air.",
      en: "Affordable studio at Margonda Residence 5, integrated with D'Mall Depok. Only 10 minutes walk to Depok Baru Station and University of Indonesia. Best choice for UI, Gunadarma, and Pancasila University students. Electricity and water bills included.",
    },
    ownerName: "Siti Nurhaliza",
    ownerPhone: "6281234501014",
    ownerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
    rating: 4.5,
    reviews: 334,
    ratingSource: "Booking.com 8.9/10",
    featured: false,
    verified: true,
    available: true,
    tags: ["Dekat UI", "Student Friendly", "Termurah", "D'Mall"],
    createdAt: "2024-03-05",
  },
  {
    id: "15",
    title: "Bogor Icon – 1BR Kota Hujan Premium",
    slug: "bogor-icon-1br-kota-hujan",
    location: "Jl. Pajajaran No.1, Bantarjati – Bogor Utara",
    city: "bogor",
    type: "1br",
    price: 3800000,
    priceUnit: "bulan",
    size: 36,
    floor: 11,
    totalFloors: 25,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
      "https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "security", "furnished", "elevator", "parking"],
    description: {
      id: "Unit 1BR premium di Bogor Icon, landmark baru kota Bogor. Fully furnished dengan view Gunung Salak dan Gunung Gede yang memukau. Fasilitas modern: kolam renang, keamanan 24 jam. Dekat Stasiun Bogor KRL, Kebun Raya Bogor, Botani Square Mall, dan akses Tol Jagorawi.",
      en: "Premium 1BR unit at Bogor Icon, Bogor city's new landmark. Fully furnished with stunning views of Mount Salak and Mount Gede. Modern facilities: swimming pool, 24-hour security. Near Bogor KRL Station, Bogor Botanical Garden, Botani Square Mall, and Jagorawi Toll access.",
    },
    ownerName: "Dian Purnama",
    ownerPhone: "6281234501015",
    ownerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    rating: 4.5,
    reviews: 123,
    ratingSource: "Agoda 8.8/10",
    featured: false,
    verified: true,
    available: true,
    tags: ["Mountain View", "Dekat KRL", "Botani Square", "Bogor"],
    createdAt: "2024-02-25",
  },
  {
    id: "16",
    title: "Bintaro Plaza Residences – 2BR Gateway Selatan",
    slug: "bintaro-plaza-residences-2br",
    location: "Jl. Bintaro Utama Sektor 3A, Bintaro – Tangerang Selatan",
    city: "tangerang",
    type: "2br",
    price: 6800000,
    priceUnit: "bulan",
    size: 60,
    floor: 16,
    totalFloors: 28,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
      "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=800&q=80",
      "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "balcony"],
    description: {
      id: "Unit 2BR di Bintaro Plaza Residences, terintegrasi langsung dengan Bintaro Exchange Mall. Fully furnished premium dengan balkon. Fasilitas lengkap: kolam renang, gym, jogging track. Dekat RS Internasional Bintaro, Swiss German University, dan akses tol Ulujami. Cocok untuk profesional dan keluarga yang menginginkan hunian terintegrasi kota mandiri.",
      en: "2BR unit at Bintaro Plaza Residences, directly integrated with Bintaro Exchange Mall. Premium fully furnished with balcony. Complete facilities: swimming pool, gym, jogging track. Near Bintaro International Hospital, Swiss German University, and Ulujami toll access. Suitable for professionals and families wanting an integrated self-contained city residence.",
    },
    ownerName: "Farid Wajdi",
    ownerPhone: "6281234501016",
    ownerAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&q=80",
    rating: 4.7,
    reviews: 198,
    ratingSource: "Google Maps 4.5★",
    featured: true,
    verified: true,
    available: true,
    tags: ["Integrated Mall", "Bintaro", "Balkon", "Premium"],
    createdAt: "2024-01-30",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BATCH 2 — 10 listing baru hasil riset publik (Booking.com, Agoda, VRBO,
  //            apartemenrumah.com, apartemenmewah.com — Juni 2024)
  // Sumber: harga market 2024, nama & lokasi real, WA unik per pemilik
  // ══════════════════════════════════════════════════════════════════════════

  // ── JAKARTA PUSAT ─────────────────────────────────────────────────────────
  {
    id: "17",
    title: "Thamrin Residence – 1BR City View Bundaran HI",
    slug: "thamrin-residence-1br-bundaran-hi",
    location: "Jl. KH Mas Mansyur No.1, Tanah Abang – Jakarta Pusat",
    city: "jakarta",
    type: "1br",
    price: 6500000,
    priceUnit: "bulan",
    size: 36,
    floor: 24,
    totalFloors: 42,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "balcony"],
    description: {
      id: "Unit 1BR di Thamrin Residence Tower C lantai 24 dengan view Bundaran HI dan kota Jakarta yang memukau. Hanya 150m dari Bundaran HI, walking distance ke Grand Indonesia, Plaza Indonesia, dan berbagai kantor di Sudirman-Thamrin. Fully furnished modern: AC, smart TV, springbed, lemari, dapur set, water heater. Fasilitas gedung: olympic pool, gym, 24h security, concierge.",
      en: "1BR unit at Thamrin Residence Tower C on the 24th floor with stunning Bundaran HI and Jakarta city views. Only 150m from Bundaran HI, walking distance to Grand Indonesia, Plaza Indonesia, and various offices on Sudirman-Thamrin. Fully furnished: AC, smart TV, spring bed, wardrobe, kitchen set, water heater. Building: olympic pool, gym, 24h security, concierge.",
    },
    ownerName: "Surya Atmaja",
    ownerPhone: "628170000017",
    ownerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    rating: 4.8,
    reviews: 521,
    ratingSource: "Booking.com 10/10",
    featured: true,
    verified: true,
    available: true,
    tags: ["Bundaran HI", "City View", "Walking to Mall", "Premium"],
    createdAt: "2024-04-01",
  },
  {
    id: "18",
    title: "Thamrin Residence – Studio Cozy Pusat Kota",
    slug: "thamrin-residence-studio-cozy",
    location: "Jl. KH Mas Mansyur No.1, Tanah Abang – Jakarta Pusat",
    city: "jakarta",
    type: "studio",
    price: 4200000,
    priceUnit: "bulan",
    size: 28,
    floor: 18,
    totalFloors: 42,
    bedrooms: 0,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&q=80",
      "https://images.unsplash.com/photo-1505873242700-f289a29e1724?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "security", "furnished", "elevator", "gym"],
    description: {
      id: "Studio compact nan cozy di Thamrin Residence, lokasi paling strategis di Jakarta Pusat. Dekat Stasiun MRT Bundaran HI, Trans Jakarta, dan berbagai pusat perbelanjaan premium. Fully furnished lengkap, unit bersih terawat. Cocok untuk profesional yang bekerja di area SCBD, Sudirman, dan Kuningan.",
      en: "Compact and cozy studio at Thamrin Residence, the most strategic location in Central Jakarta. Near MRT Bundaran HI Station, Trans Jakarta, and various premium shopping centers. Fully furnished, clean and well-maintained unit. Perfect for professionals working in SCBD, Sudirman, and Kuningan areas.",
    },
    ownerName: "Melinda Sari",
    ownerPhone: "628170000018",
    ownerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    rating: 4.8,
    reviews: 489,
    ratingSource: "Booking.com 10/10",
    featured: false,
    verified: true,
    available: true,
    tags: ["MRT Dekat", "Pusat Kota", "Furnished", "Strategis"],
    createdAt: "2024-04-05",
  },

  // ── JAKARTA BARAT ─────────────────────────────────────────────────────────
  {
    id: "19",
    title: "Central Park Residences – 2BR Direct Access Mall",
    slug: "central-park-residences-2br-direct-mall",
    location: "Jl. Letjen S Parman Kav. 28, Tanjung Duren – Jakarta Barat",
    city: "jakarta",
    type: "2br",
    price: 9500000,
    priceUnit: "bulan",
    size: 72,
    floor: 20,
    totalFloors: 32,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
      "https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800&q=80",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "kitchen", "laundry"],
    description: {
      id: "Unit 2BR eksklusif di Central Park Residences dengan akses langsung ke Central Park Mall. Olimpiade swimming pool, gym center, laundry, Alfamart di dalam gedung. Sistem kartu akses single-entry, hanya 8 unit per lantai. Fully furnished premium: 2 AC, 2 springbed, sofa, dapur lengkap, water heater. Dekat Bandara Soetta via tol, akses LRT Jabodebek.",
      en: "Exclusive 2BR unit at Central Park Residences with direct access to Central Park Mall. Olympic swimming pool, gym center, laundry, Alfamart inside building. Single-entry card system, only 8 units per floor. Premium fully furnished: 2 ACs, 2 spring beds, sofa, full kitchen, water heater. Near Soetta Airport via toll, LRT Jabodebek access.",
    },
    ownerName: "Kevin Pratama",
    ownerPhone: "628170000019",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    rating: 4.9,
    reviews: 413,
    ratingSource: "Booking.com 9.9/10",
    featured: true,
    verified: true,
    available: true,
    tags: ["Direct Mall Access", "Olympic Pool", "8 Unit/Lantai", "Premium"],
    createdAt: "2024-04-08",
  },
  {
    id: "20",
    title: "Taman Anggrek Residences – 2BR Full Furnished Tanjung Duren",
    slug: "taman-anggrek-residences-2br-tanjung-duren",
    location: "Jl. Tanjung Duren Timur 2, Tanjung Duren – Jakarta Barat",
    city: "jakarta",
    type: "2br",
    price: 7800000,
    priceUnit: "bulan",
    size: 50,
    floor: 15,
    totalFloors: 30,
    bedrooms: 2,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
      "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80",
      "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "kitchen"],
    description: {
      id: "Unit 2BR fully furnished di Taman Anggrek Residences Tower Espiritu. Kondisi unit sangat terawat: 3 AC, water heater, kitchen set lengkap dengan kompor listrik tanam, lemari pakaian. Fasilitas gedung: gym, swimming pool, tennis court, basketball court. Terintegrasi dengan Taman Anggrek Mall. Sangat cocok untuk pasangan atau profesional.",
      en: "Fully furnished 2BR unit at Taman Anggrek Residences, Espiritu Tower. Well-maintained unit: 3 ACs, water heater, complete kitchen set with built-in electric stove, wardrobe. Building facilities: gym, swimming pool, tennis court, basketball court. Integrated with Taman Anggrek Mall. Perfect for couples or professionals.",
    },
    ownerName: "Sandra Wijaya",
    ownerPhone: "628170000020",
    ownerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
    rating: 4.7,
    reviews: 387,
    ratingSource: "Booking.com 8.2/10",
    featured: true,
    verified: true,
    available: true,
    tags: ["Tennis Court", "3 AC", "Mall Terintegrasi", "Terawat"],
    createdAt: "2024-04-10",
  },
  {
    id: "21",
    title: "Puri Orchard Cengkareng – 1BR Dekat Bandara & PIK",
    slug: "puri-orchard-cengkareng-1br",
    location: "Jl. Lingkar Luar Barat, Rawa Buaya – Cengkareng, Jakarta Barat",
    city: "jakarta",
    type: "1br",
    price: 3800000,
    priceUnit: "bulan",
    size: 32,
    floor: 10,
    totalFloors: 25,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "security", "furnished", "elevator", "parking"],
    description: {
      id: "Unit 1BR di Puri Orchard, apartemen modern di Jakarta Barat. Hanya 30 menit dari Bandara Soekarno-Hatta. Dekat Lippo Mall Puri, Puri Indah Mall, RS Pondok Indah, dan akses tol menuju PIK. Fully furnished: AC, TV, springbed, lemari. Cocok untuk karyawan yang bekerja di kawasan barat Jakarta atau yang sering bepergian via bandara.",
      en: "1BR unit at Puri Orchard, a modern apartment in West Jakarta. Only 30 minutes from Soekarno-Hatta Airport. Near Lippo Mall Puri, Puri Indah Mall, Pondok Indah Hospital, and toll access to PIK. Fully furnished: AC, TV, spring bed, wardrobe. Ideal for employees working in West Jakarta or frequent airport travelers.",
    },
    ownerName: "Hadi Gunawan",
    ownerPhone: "628170000021",
    ownerAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&q=80",
    rating: 4.4,
    reviews: 156,
    ratingSource: "Booking.com 8.4/10",
    featured: false,
    verified: true,
    available: true,
    tags: ["Dekat Bandara", "Dekat PIK", "Affordable", "Jakarta Barat"],
    createdAt: "2024-04-12",
  },

  // ── JAKARTA SELATAN ───────────────────────────────────────────────────────
  {
    id: "22",
    title: "The Mansion at Kemang – 1BR Rooftop Pool & Gym",
    slug: "the-mansion-kemang-1br-rooftop-pool",
    location: "Jl. Kemang Raya No.1, Bangka – Mampang Prapatan, Jakarta Selatan",
    city: "jakarta",
    type: "1br",
    price: 8500000,
    priceUnit: "bulan",
    size: 45,
    floor: 20,
    totalFloors: 38,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "balcony", "pet"],
    description: {
      id: "Unit 1BR eksklusif di The Mansion at Kemang, landmark apartemen premium di jantung kawasan Kemang. Outdoor rooftop pool, gym 24 jam, BBQ area, dan view selatan Jakarta yang cantik dari balkon. Pet friendly. Dekat dengan berbagai restoran, café, bar, dan pusat hiburan Kemang. Walking distance ke Blok M. Cocok untuk profesional dan ekspatriat.",
      en: "Exclusive 1BR unit at The Mansion at Kemang, a premium apartment landmark in the heart of Kemang. Rooftop pool, 24-hour gym, BBQ area, and beautiful south Jakarta view from the balcony. Pet friendly. Near various restaurants, cafés, bars, and Kemang entertainment centers. Walking distance to Blok M. Perfect for professionals and expats.",
    },
    ownerName: "Jessica Tanoto",
    ownerPhone: "628170000022",
    ownerAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&q=80",
    rating: 4.9,
    reviews: 298,
    ratingSource: "Hotels.com 9.2/10",
    featured: true,
    verified: true,
    available: true,
    tags: ["Kemang", "Rooftop Pool", "Pet Friendly", "Expat Area"],
    createdAt: "2024-04-15",
  },

  // ── JAKARTA UTARA ─────────────────────────────────────────────────────────
  {
    id: "23",
    title: "Gading Nias Residence – Studio Kelapa Gading Terjangkau",
    slug: "gading-nias-residence-studio-kelapa-gading",
    location: "Jl. Gading Nias Raya, Kelapa Gading – Jakarta Utara",
    city: "jakarta",
    type: "studio",
    price: 2400000,
    priceUnit: "bulan",
    size: 22,
    floor: 8,
    totalFloors: 20,
    bedrooms: 0,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "security", "furnished", "elevator", "laundry"],
    description: {
      id: "Studio terjangkau di Gading Nias Residence, kawasan Kelapa Gading yang terkenal dengan kuliner dan lifestyle. Unit compact dan bersih, fully furnished: AC, TV, springbed, lemari. Dekat La Piazza, Mall Kelapa Gading, berbagai foodcourt legendaris Kelapa Gading, dan akses tol Ancol. Cocok untuk pekerja muda dan pasangan.",
      en: "Affordable studio at Gading Nias Residence, Kelapa Gading area famous for culinary and lifestyle. Clean compact unit, fully furnished: AC, TV, spring bed, wardrobe. Near La Piazza, Kelapa Gading Mall, various legendary Kelapa Gading food courts, and Ancol toll access. Perfect for young workers and couples.",
    },
    ownerName: "Tommy Halim",
    ownerPhone: "628170000023",
    ownerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
    rating: 4.3,
    reviews: 167,
    ratingSource: "Agoda 8.3/10",
    featured: false,
    verified: true,
    available: true,
    tags: ["Kelapa Gading", "Kuliner Dekat", "Budget", "Terjangkau"],
    createdAt: "2024-04-18",
  },

  // ── JAKARTA TIMUR ─────────────────────────────────────────────────────────
  {
    id: "24",
    title: "Bassura City – 1BR Pool View Jatinegara",
    slug: "bassura-city-1br-pool-view-jatinegara",
    location: "Jl. Jend. Basuki Rachmat No.1, Cipinang Besar Selatan – Jatinegara, Jakarta Timur",
    city: "jakarta",
    type: "1br",
    price: 4500000,
    priceUnit: "bulan",
    size: 36,
    floor: 20,
    totalFloors: 38,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&q=80",
      "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "balcony"],
    description: {
      id: "Unit 1BR di Bassura City Tower B lantai 20 dengan pool view yang indah. Fully furnished premium: AC Daikin, smart TV, springbed premium, lemari besar, dapur set. Fasilitas superblock terlengkap: Bassura Mall di dalam gedung, kolam renang private, gym modern, foodcourt, minimarket, ATM center. Dekat Tol Dalam Kota dan Trans Jakarta.",
      en: "1BR unit at Bassura City Tower B, 20th floor with beautiful pool view. Premium fully furnished: Daikin AC, smart TV, premium spring bed, large wardrobe, kitchen set. Complete superblock facilities: Bassura Mall inside building, private swimming pool, modern gym, food court, minimarket, ATM center. Near Jakarta Inner Ring Road and Trans Jakarta.",
    },
    ownerName: "Benny Setiawan",
    ownerPhone: "628170000024",
    ownerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    rating: 4.7,
    reviews: 312,
    ratingSource: "Booking.com",
    featured: true,
    verified: true,
    available: true,
    tags: ["Pool View", "Superblock", "Bassura Mall", "Jatinegara"],
    createdAt: "2024-04-20",
  },
  {
    id: "25",
    title: "Sentra Timur Residence – 1BR Dekat Tol Pulogebang",
    slug: "sentra-timur-residence-1br-pulogebang",
    location: "Jl. Sentra Primer Timur Baru, Pulo Gebang – Cakung, Jakarta Timur",
    city: "jakarta",
    type: "1br",
    price: 3200000,
    priceUnit: "bulan",
    size: 33,
    floor: 12,
    totalFloors: 25,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "security", "furnished", "elevator", "parking"],
    description: {
      id: "Unit 1BR fully furnished di Sentra Timur Residence, apartemen modern di Jakarta Timur. Dekat pintu tol Pulogebang yang terhubung ke tol Jakarta-Cikampek. Akses mudah ke Bekasi, Karawang, dan pusat kota. Fasilitas kolam renang, keamanan 24 jam. Cocok untuk pekerja commuter antara Jakarta-Bekasi.",
      en: "Fully furnished 1BR unit at Sentra Timur Residence, a modern apartment in East Jakarta. Near Pulogebang toll gate connecting to Jakarta-Cikampek toll. Easy access to Bekasi, Karawang, and the city center. Swimming pool, 24-hour security facilities. Ideal for Jakarta-Bekasi commuter workers.",
    },
    ownerName: "Eko Prasetyo",
    ownerPhone: "628170000025",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    rating: 4.2,
    reviews: 76,
    ratingSource: "Google Maps 4.1★",
    featured: false,
    verified: false,
    available: true,
    tags: ["Dekat Tol", "Commuter", "Jakarta Timur", "Affordable"],
    createdAt: "2024-04-22",
  },

  // ── DEPOK ─────────────────────────────────────────────────────────────────
  {
    id: "26",
    title: "Atlanta Residences Depok – 1BR Dekat Stasiun KRL",
    slug: "atlanta-residences-depok-1br-krl",
    location: "Jl. Margonda Raya No.580, Kemiri Muka – Beji, Depok",
    city: "depok",
    type: "1br",
    price: 2800000,
    priceUnit: "bulan",
    size: 30,
    floor: 7,
    totalFloors: 18,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
      "https://images.unsplash.com/photo-1505873242700-f289a29e1724?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "security", "furnished", "elevator", "laundry", "pool"],
    description: {
      id: "Unit 1BR di Atlanta Residences Depok, 5 menit berjalan kaki ke Stasiun Depok Baru KRL. Fully furnished lengkap dan nyaman. Sangat strategis di Jl. Margonda Raya — dekat Universitas Indonesia, Gunadarma, berbagai kampus, supermarket, café, dan pusat kuliner Margonda. Cocok untuk mahasiswa dan profesional yang commute ke Jakarta.",
      en: "1BR unit at Atlanta Residences Depok, 5 minutes walking to Depok Baru KRL Station. Fully furnished, complete and comfortable. Very strategic on Jl. Margonda Raya — near University of Indonesia, Gunadarma, various campuses, supermarkets, cafés, and Margonda culinary centers. Perfect for students and professionals commuting to Jakarta.",
    },
    ownerName: "Putri Andriani",
    ownerPhone: "628170000026",
    ownerAvatar: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=100&q=80",
    rating: 4.5,
    reviews: 143,
    ratingSource: "Google Maps 4.4★",
    featured: false,
    verified: true,
    available: true,
    tags: ["5 Menit KRL", "Margonda", "Dekat UI", "Value"],
    createdAt: "2024-04-25",
  },
];

export const STATS = [
  { value: 2940, suffix: "+", label: { id: "Listing Aktif", en: "Active Listings" } },
  { value: 5, suffix: " Kota", label: { id: "Area JABODETABEK", en: "JABODETABEK Areas" } },
  { value: 12500, suffix: "+", label: { id: "Penyewa Puas", en: "Happy Tenants" } },
  { value: 98, suffix: "%", label: { id: "Tingkat Kepuasan", en: "Satisfaction Rate" } },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Andi Wijaksono",
    role: { id: "Software Engineer, Jakarta", en: "Software Engineer, Jakarta" },
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
    rating: 5,
    text: {
      id: "SewaApartement benar-benar memudahkan saya menemukan apartemen yang tepat. Dalam waktu 3 hari langsung dapat unit Branz Simatupang yang sesuai budget. Prosesnya mudah dan langsung bisa contact owner via WhatsApp!",
      en: "SewaApartement really made it easy for me to find the right apartment. Within 3 days I got a Branz Simatupang unit that fits my budget. The process is easy and I can directly contact the owner via WhatsApp!",
    },
  },
  {
    id: 2,
    name: "Maya Pertiwi",
    role: { id: "Mahasiswi UI, Depok", en: "UI Student, Depok" },
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
    rating: 5,
    text: {
      id: "Sebagai mahasiswi baru di Depok, saya sangat terbantu. Nemu Margonda Residence 5 yang harganya super terjangkau dan dekat banget sama kampus UI. Langsung chat WhatsApp pemilik, deal dalam sehari!",
      en: "As a new student in Depok, I was greatly helped. Found Margonda Residence 5 at a super affordable price and very close to UI campus. Directly WhatsApp chatted with the owner, deal in one day!",
    },
  },
  {
    id: 3,
    name: "Budi Kurniawan",
    role: { id: "Pemilik Apartemen, BSD", en: "Apartment Owner, BSD" },
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    rating: 5,
    text: {
      id: "Saya sudah daftarkan 2 unit di Roseville BSD dan Casa de Parco. Dalam seminggu langsung ada yang menghubungi via WhatsApp. Dashboard pemilik sangat mudah digunakan untuk manage listing.",
      en: "I have registered 2 units at Roseville BSD and Casa de Parco. Within a week there were already inquiries via WhatsApp. The owner dashboard is very easy to use to manage listings.",
    },
  },
  {
    id: 4,
    name: "Sarah Chen",
    role: { id: "Ekspatriat, SCBD Jakarta", en: "Expat, SCBD Jakarta" },
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    rating: 5,
    text: {
      id: "Fitur bilingual sangat membantu saya sebagai ekspatriat. Informasi Anandamaya Residence jelas dan lengkap. Bisa langsung WhatsApp owner tanpa perantara. Found my dream apartment here!",
      en: "The bilingual feature really helps me as an expat. Anandamaya Residence information is clear and complete. Can directly WhatsApp the owner without intermediaries. Found my dream apartment here!",
    },
  },
];

export const HOW_IT_WORKS_TENANT = [
  {
    step: 1,
    icon: "🔍",
    title: { id: "Cari Apartemen", en: "Search Apartment" },
    desc: { id: "Gunakan filter kota, harga, tipe, dan fasilitas untuk menemukan apartemen yang sesuai kebutuhan.", en: "Use city, price, type, and amenity filters to find the apartment that suits your needs." },
  },
  {
    step: 2,
    icon: "👀",
    title: { id: "Lihat Detail", en: "View Details" },
    desc: { id: "Cek foto lengkap, fasilitas, lokasi di peta, dan semua informasi yang Anda butuhkan.", en: "Check complete photos, amenities, location on the map, and all the information you need." },
  },
  {
    step: 3,
    icon: "💬",
    title: { id: "Hubungi Pemilik", en: "Contact Owner" },
    desc: { id: "Langsung hubungi pemilik via WhatsApp untuk negosiasi harga dan jadwal survei.", en: "Directly contact the owner via WhatsApp to negotiate prices and schedule a survey." },
  },
  {
    step: 4,
    icon: "🏠",
    title: { id: "Sewa & Tinggal", en: "Rent & Move In" },
    desc: { id: "Setelah deal dengan pemilik, langsung pindah ke apartemen impian Anda!", en: "After a deal with the owner, move directly into your dream apartment!" },
  },
];

export const HOW_IT_WORKS_OWNER = [
  {
    step: 1,
    icon: "📝",
    title: { id: "Daftar Akun", en: "Register Account" },
    desc: { id: "Buat akun pemilik gratis dalam hitungan menit. Verifikasi identitas untuk meningkatkan kepercayaan.", en: "Create a free owner account in minutes. Verify identity to increase trust." },
  },
  {
    step: 2,
    icon: "📸",
    title: { id: "Upload Listing", en: "Upload Listing" },
    desc: { id: "Upload foto properti, isi detail lengkap, tentukan harga, dan pilih fasilitas yang tersedia.", en: "Upload property photos, fill in complete details, set prices, and select available amenities." },
  },
  {
    step: 3,
    icon: "✅",
    title: { id: "Listing Aktif", en: "Listing Active" },
    desc: { id: "Listing Anda akan langsung aktif dan terlihat oleh ribuan pencari apartemen.", en: "Your listing will be immediately active and visible to thousands of apartment seekers." },
  },
  {
    step: 4,
    icon: "📞",
    title: { id: "Terima Calon Penyewa", en: "Receive Tenants" },
    desc: { id: "Calon penyewa akan menghubungi langsung via WhatsApp yang Anda daftarkan.", en: "Prospective tenants will contact you directly via WhatsApp that you registered." },
  },
];

export const BLOG_POSTS = [
  {
    id: "seed-blog-001",
    slug: "tips-sewa-apartemen-jakarta-pertama-kali",
    title: { id: "10 Tips Sewa Apartemen di Jakarta untuk Pertama Kali", en: "10 Tips for Renting an Apartment in Jakarta for the First Time" },
    excerpt: { id: "Menyewa apartemen pertama kali di Jakarta bisa terasa membingungkan. Berikut panduan lengkap agar Anda tidak salah pilih.", en: "Renting an apartment for the first time in Jakarta can feel confusing. Here is a complete guide so you don't make the wrong choice." },
    category: { id: "Panduan", en: "Guide" },
    image: "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=600&q=80",
    author: "Tim Redaksi",
    date: "2024-03-01",
    readTime: 7,
  },
  {
    id: "seed-blog-002",
    slug: "perbandingan-harga-apartemen-jabodetabek-2024",
    title: { id: "Perbandingan Harga Apartemen JABODETABEK 2024", en: "JABODETABEK Apartment Price Comparison 2024" },
    excerpt: { id: "Analisis lengkap harga sewa apartemen di Jakarta, Bogor, Depok, Tangerang, dan Bekasi. Mana yang paling terjangkau?", en: "Complete analysis of apartment rental prices in Jakarta, Bogor, Depok, Tangerang, and Bekasi. Which is the most affordable?" },
    category: { id: "Analisis Pasar", en: "Market Analysis" },
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80",
    author: "Analis Properti",
    date: "2024-02-20",
    readTime: 10,
  },
  {
    id: "seed-blog-003",
    slug: "apartemen-terbaik-untuk-mahasiswa-depok",
    title: { id: "Rekomendasi Apartemen Terbaik untuk Mahasiswa di Depok", en: "Best Apartment Recommendations for Students in Depok" },
    excerpt: { id: "Daftar apartemen terbaik di Depok dengan harga ramah mahasiswa, lengkap dengan fasilitas dan akses transportasi.", en: "List of the best apartments in Depok with student-friendly prices, complete with facilities and transportation access." },
    category: { id: "Rekomendasi", en: "Recommendation" },
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    author: "Tim Redaksi",
    date: "2024-02-10",
    readTime: 5,
  },
];

export const FAQS = [
  {
    q: { id: "Apakah pendaftaran sebagai pemilik gratis?", en: "Is registration as an owner free?" },
    a: { id: "Ya, pendaftaran dan upload listing pertama Anda sepenuhnya gratis. Nikmati layanan dasar tanpa biaya apapun.", en: "Yes, registration and uploading your first listing is completely free. Enjoy basic services at no cost." },
  },
  {
    q: { id: "Bagaimana cara calon penyewa menghubungi saya?", en: "How do potential tenants contact me?" },
    a: { id: "Calon penyewa akan langsung menghubungi Anda melalui nomor WhatsApp yang Anda daftarkan di profil dan listing.", en: "Potential tenants will directly contact you through the WhatsApp number you registered in your profile and listing." },
  },
  {
    q: { id: "Apakah ada proses verifikasi untuk listing?", en: "Is there a verification process for listings?" },
    a: { id: "Ya, tim kami melakukan verifikasi dasar untuk memastikan keaslian listing. Pemilik yang terverifikasi mendapat badge khusus.", en: "Yes, our team does basic verification to ensure the authenticity of listings. Verified owners get a special badge." },
  },
  {
    q: { id: "Berapa lama listing saya aktif?", en: "How long will my listing be active?" },
    a: { id: "Listing aktif selama 90 hari dan dapat diperpanjang kapan saja melalui dashboard pemilik.", en: "Listings are active for 90 days and can be renewed at any time through the owner dashboard." },
  },
  {
    q: { id: "Apakah platform ini aman?", en: "Is this platform safe?" },
    a: { id: "Keamanan adalah prioritas kami. Semua pengguna terverifikasi, dan kami memiliki sistem pelaporan untuk konten yang mencurigakan.", en: "Security is our priority. All users are verified, and we have a reporting system for suspicious content." },
  },
];

