export const SITE_NAME = "SewaApartement";
export const SITE_TAGLINE = {
  id: "Platform Sewa Apartemen #1 di JABODETABEK",
  en: "The #1 Apartment Rental Platform in JABODETABEK",
};
export const SITE_DESC = {
  id: "Temukan apartemen impian Anda di Jakarta, Bogor, Depok, Tangerang, dan Bekasi. Ribuan pilihan untuk mahasiswa, pekerja, dan keluarga.",
  en: "Find your dream apartment in Jakarta, Bogor, Depok, Tangerang, and Bekasi. Thousands of options for students, workers, and families.",
};

export const CITIES = [
  { id: "jakarta", name: "Jakarta", icon: "🏙️", count: 1240 },
  { id: "bogor", name: "Bogor", icon: "🌿", count: 320 },
  { id: "depok", name: "Depok", icon: "🏫", count: 410 },
  { id: "tangerang", name: "Tangerang", icon: "✈️", count: 580 },
  { id: "bekasi", name: "Bekasi", icon: "🏭", count: 390 },
];

export const APARTMENT_TYPES = [
  { id: "studio", label: { id: "Studio", en: "Studio" } },
  { id: "1br", label: { id: "1 Kamar", en: "1 Bedroom" } },
  { id: "2br", label: { id: "2 Kamar", en: "2 Bedrooms" } },
  { id: "3br", label: { id: "3 Kamar", en: "3 Bedrooms" } },
  { id: "penthouse", label: { id: "Penthouse", en: "Penthouse" } },
];

export const RENT_DURATIONS = [
  { id: "harian", label: { id: "Harian", en: "Daily" } },
  { id: "bulanan", label: { id: "Bulanan", en: "Monthly" } },
  { id: "tahunan", label: { id: "Tahunan", en: "Yearly" } },
];

export const PRICE_RANGES = [
  { id: "0-2jt", label: { id: "< Rp 2 Juta/bln", en: "< Rp 2M/month" }, min: 0, max: 2000000 },
  { id: "2-4jt", label: { id: "Rp 2–4 Juta/bln", en: "Rp 2–4M/month" }, min: 2000000, max: 4000000 },
  { id: "4-7jt", label: { id: "Rp 4–7 Juta/bln", en: "Rp 4–7M/month" }, min: 4000000, max: 7000000 },
  { id: "7-15jt", label: { id: "Rp 7–15 Juta/bln", en: "Rp 7–15M/month" }, min: 7000000, max: 15000000 },
  { id: "15jt+", label: { id: "> Rp 15 Juta/bln", en: "> Rp 15M/month" }, min: 15000000, max: 999999999 },
];

export const AMENITIES = [
  { id: "wifi", icon: "📶", label: { id: "WiFi", en: "WiFi" } },
  { id: "ac", icon: "❄️", label: { id: "AC", en: "AC" } },
  { id: "parking", icon: "🚗", label: { id: "Parkir", en: "Parking" } },
  { id: "pool", icon: "🏊", label: { id: "Kolam Renang", en: "Pool" } },
  { id: "gym", icon: "🏋️", label: { id: "Gym", en: "Gym" } },
  { id: "security", icon: "🔒", label: { id: "Keamanan 24 Jam", en: "24H Security" } },
  { id: "laundry", icon: "👕", label: { id: "Laundry", en: "Laundry" } },
  { id: "kitchen", icon: "🍳", label: { id: "Dapur", en: "Kitchen" } },
  { id: "balcony", icon: "🌅", label: { id: "Balkon", en: "Balcony" } },
  { id: "pet", icon: "🐾", label: { id: "Pet Friendly", en: "Pet Friendly" } },
  { id: "furnished", icon: "🛋️", label: { id: "Fully Furnished", en: "Fully Furnished" } },
  { id: "elevator", icon: "🛗", label: { id: "Lift", en: "Elevator" } },
];

// =====================================================================
// DATA LISTING APARTEMEN REAL JABODETABEK
// Sumber: rumah123.com, 99.co, sewa-apartemen.net, jendela360.com
// Harga sesuai market rate 2024
// =====================================================================
export const SAMPLE_LISTINGS = [
  // ── JAKARTA ──────────────────────────────────────────────────────────
  {
    id: "1",
    title: "Bassura City Tower A – Studio Full Furnished",
    slug: "bassura-city-tower-a-studio",
    location: "Jl. Basuki Rahmat, Cipinang Besar Selatan, Jatinegara – Jakarta Timur",
    city: "jakarta",
    type: "studio",
    price: 2800000,
    priceUnit: "bulan",
    size: 26,
    floor: 15,
    totalFloors: 38,
    bedrooms: 0,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80",
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "laundry"],
    description: {
      id: "Unit studio di Bassura City Tower A lantai 15, fully furnished. Apartemen ini dilengkapi AC, smart TV, springbed, lemari, kulkas, dan kitchenset. Fasilitas gedung lengkap: kolam renang, gym, mini market, ATM center. Dekat Tol Dalam Kota, Trans Jakarta, dan pusat perbelanjaan Bassura Mall.",
      en: "Studio unit at Bassura City Tower A on the 15th floor, fully furnished. The apartment includes AC, smart TV, spring bed, wardrobe, refrigerator, and kitchen set. Complete building facilities: swimming pool, gym, mini market, ATM center. Close to Tol Dalam Kota, Trans Jakarta, and Bassura Mall.",
    },
    ownerName: "Hendra Kusuma",
    ownerPhone: "628118696940",
    ownerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    rating: 4.6,
    reviews: 34,
    featured: true,
    verified: true,
    available: true,
    tags: ["Furnished", "Pool", "Dekat Mall", "Trans Jakarta"],
    createdAt: "2024-03-10",
  },
  {
    id: "2",
    title: "Kalibata City – 2BR View Kota Strategis",
    slug: "kalibata-city-2br-view-kota",
    location: "Jl. Raya Kalibata No.1, Kalibata – Jakarta Selatan",
    city: "jakarta",
    type: "2br",
    price: 5500000,
    priceUnit: "bulan",
    size: 50,
    floor: 21,
    totalFloors: 32,
    bedrooms: 2,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
      "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80",
      "https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "kitchen"],
    description: {
      id: "Unit 2 kamar tidur di Kalibata City lantai 21 dengan view kota Jakarta yang indah. Fully furnished lengkap: 2 AC, 2 springbed, lemari pakaian, meja makan, sofa, dan dapur set. Fasilitas gedung sangat lengkap termasuk kolam renang olimpiade, gym, food court, sekolah, klinik, dan supermarket. Dekat Stasiun Kalibata KRL dan pintu tol.",
      en: "2-bedroom unit at Kalibata City on the 21st floor with beautiful Jakarta city views. Fully furnished: 2 ACs, 2 spring beds, wardrobe, dining table, sofa, and kitchen set. Complete building facilities including Olympic swimming pool, gym, food court, school, clinic, and supermarket. Near Kalibata KRL Station and toll gate.",
    },
    ownerName: "Sari Dewi Lestari",
    ownerPhone: "628118696940",
    ownerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    rating: 4.7,
    reviews: 41,
    featured: true,
    verified: true,
    available: true,
    tags: ["City View", "Dekat KRL", "Fully Furnished", "Pool Olimpiade"],
    createdAt: "2024-02-15",
  },
  {
    id: "3",
    title: "Green Pramuka City – 1BR Cempaka Putih",
    slug: "green-pramuka-city-1br-cempaka-putih",
    location: "Jl. Pramuka Raya, Cempaka Putih – Jakarta Pusat",
    city: "jakarta",
    type: "1br",
    price: 4200000,
    priceUnit: "bulan",
    size: 35,
    floor: 18,
    totalFloors: 30,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
      "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "laundry"],
    description: {
      id: "Unit 1BR di Green Pramuka City lantai 18 dengan view mountain dan kota. Fully furnished modern: AC, TV LED, springbed Queen, lemari, kulkas, dan water heater. Kompleks apartemen super lengkap dilengkapi mall (Green Pramuka Square), food court, sekolah, klinik, dan sarana olahraga. Akses mudah ke Jl. Ahmad Yani dan RSPAD.",
      en: "1BR unit at Green Pramuka City on the 18th floor with mountain and city views. Modern fully furnished: AC, LED TV, Queen spring bed, wardrobe, refrigerator, and water heater. Super complete apartment complex with mall (Green Pramuka Square), food court, school, clinic, and sports facilities. Easy access to Jl. Ahmad Yani and RSPAD.",
    },
    ownerName: "Bambang Setiawan",
    ownerPhone: "628118696940",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    rating: 4.5,
    reviews: 28,
    featured: true,
    verified: true,
    available: true,
    tags: ["Dekat Mall", "Furnished", "Mountain View", "Strategis"],
    createdAt: "2024-01-20",
  },
  {
    id: "4",
    title: "Anandamaya Residence – 2BR Premium SCBD",
    slug: "anandamaya-residence-2br-scbd",
    location: "Jl. Jend. Sudirman Kav.1, SCBD – Jakarta Selatan",
    city: "jakarta",
    type: "2br",
    price: 28000000,
    priceUnit: "bulan",
    size: 131,
    floor: 30,
    totalFloors: 48,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
      "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "balcony", "kitchen"],
    description: {
      id: "Unit 2BR eksklusif di Anandamaya Residence, salah satu apartemen paling prestisius di Jl. Sudirman SCBD Jakarta. Fully furnished mewah dengan interior premium, private lift, rooftop sky gym, sky lounge, dan infinity pool. Lokasi sangat strategis di pusat bisnis Jakarta, walking distance ke SCBD, Pacific Place, dan Kejaksaan Agung.",
      en: "Exclusive 2BR unit at Anandamaya Residence, one of the most prestigious apartments on Jl. Sudirman SCBD Jakarta. Luxury fully furnished with premium interior, private lift, rooftop sky gym, sky lounge, and infinity pool. Very strategic location in Jakarta CBD, walking distance to SCBD, Pacific Place, and Kejaksaan Agung.",
    },
    ownerName: "Michael Hartawan",
    ownerPhone: "628118696940",
    ownerAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&q=80",
    rating: 4.9,
    reviews: 19,
    featured: true,
    verified: true,
    available: true,
    tags: ["SCBD", "Luxury", "Private Lift", "Sky Pool"],
    createdAt: "2024-01-05",
  },
  {
    id: "5",
    title: "Branz Simatupang – 1BR Modern Minimalis",
    slug: "branz-simatupang-1br-modern",
    location: "Jl. TB Simatupang Kav. 38, Cilandak – Jakarta Selatan",
    city: "jakarta",
    type: "1br",
    price: 7500000,
    priceUnit: "bulan",
    size: 44,
    floor: 22,
    totalFloors: 40,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "balcony"],
    description: {
      id: "Unit 1BR modern di Branz Simatupang lantai 22 dengan balkon dan view selatan Jakarta. Fully furnished high-end: AC Daikin, smart TV 55 inch, kasur premium, dapur Miele. Fasilitas resort-like: infinity pool, sky deck, fully-equipped gym, co-working space, dan BBQ area. Dekat Cilandak Town Square, AEON Mall, dan akses tol JORR.",
      en: "Modern 1BR unit at Branz Simatupang on the 22nd floor with balcony and south Jakarta views. High-end fully furnished: Daikin AC, 55-inch smart TV, premium mattress, Miele kitchen. Resort-like facilities: infinity pool, sky deck, fully-equipped gym, co-working space, and BBQ area. Near Cilandak Town Square, AEON Mall, and JORR toll access.",
    },
    ownerName: "Rina Sulistyowati",
    ownerPhone: "628118696940",
    ownerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
    rating: 4.8,
    reviews: 52,
    featured: true,
    verified: true,
    available: true,
    tags: ["Sky Pool", "Co-Working", "JORR Access", "Modern"],
    createdAt: "2024-02-01",
  },
  {
    id: "6",
    title: "Permata Hijau Suites – 2BR Mewah Kebayoran",
    slug: "permata-hijau-suites-2br-kebayoran",
    location: "Jl. Arteri Permata Hijau, Kebayoran Lama – Jakarta Selatan",
    city: "jakarta",
    type: "2br",
    price: 12000000,
    priceUnit: "bulan",
    size: 80,
    floor: 12,
    totalFloors: 25,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80",
      "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80",
      "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "balcony", "pet"],
    description: {
      id: "Unit 2BR mewah di Permata Hijau Suites, kawasan residensial premium Jakarta Selatan. Luas 80 m², fully furnished premium dengan 2 kamar tidur besar, ruang keluarga luas, dan dapur lengkap. Pet friendly. Fasilitas lengkap: kolam renang, gym, playground anak, keamanan 24 jam. Dekat Grand Lucky, Pondok Indah Mall, dan RS Permata Hijau.",
      en: "Luxury 2BR unit at Permata Hijau Suites, a premium residential area in South Jakarta. 80 sqm, premium fully furnished with 2 large bedrooms, spacious living room, and complete kitchen. Pet friendly. Complete facilities: swimming pool, gym, children's playground, 24-hour security. Near Grand Lucky, Pondok Indah Mall, and Permata Hijau Hospital.",
    },
    ownerName: "Agus Prasetyo",
    ownerPhone: "628118696940",
    ownerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
    rating: 4.7,
    reviews: 37,
    featured: false,
    verified: true,
    available: true,
    tags: ["Pet Friendly", "Premium", "Dekat Mall", "Kebayoran"],
    createdAt: "2024-01-25",
  },
  {
    id: "7",
    title: "Izzara Simatupang – Studio Cozy TB Simatupang",
    slug: "izzara-simatupang-studio-cozy",
    location: "Jl. TB Simatupang No. 58, Lebak Bulus – Jakarta Selatan",
    city: "jakarta",
    type: "studio",
    price: 3500000,
    priceUnit: "bulan",
    size: 28,
    floor: 9,
    totalFloors: 22,
    bedrooms: 0,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
      "https://images.unsplash.com/photo-1505873242700-f289a29e1724?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "security", "furnished", "elevator", "laundry"],
    description: {
      id: "Studio nyaman di Izzara Simatupang, apartemen modern di kawasan TB Simatupang. Fully furnished: AC, TV, springbed, lemari, dan kitchenset. Fasilitas kolam renang dan keamanan 24 jam. Dekat MRT Lebak Bulus, Cilandak Town Square, dan berbagai kantor di koridor Simatupang.",
      en: "Cozy studio at Izzara Simatupang, a modern apartment in the TB Simatupang area. Fully furnished: AC, TV, spring bed, wardrobe, and kitchen set. Swimming pool and 24-hour security. Near MRT Lebak Bulus, Cilandak Town Square, and various offices in the Simatupang corridor.",
    },
    ownerName: "Dewi Kartika",
    ownerPhone: "628118696940",
    ownerAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&q=80",
    rating: 4.4,
    reviews: 22,
    featured: false,
    verified: true,
    available: true,
    tags: ["Dekat MRT", "Furnished", "Simatupang"],
    createdAt: "2024-03-01",
  },

  // ── TANGERANG ─────────────────────────────────────────────────────────
  {
    id: "8",
    title: "Roseville SOHO & Suite BSD – 1BR Eksklusif",
    slug: "roseville-soho-suite-bsd-1br",
    location: "Jl. Pahlawan Seribu, Sunburst BSD City – Tangerang Selatan",
    city: "tangerang",
    type: "1br",
    price: 5800000,
    priceUnit: "bulan",
    size: 40,
    floor: 8,
    totalFloors: 20,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800&q=80",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking"],
    description: {
      id: "Unit 1 bedroom eksklusif di Roseville SOHO & Suite, apartemen premium di jantung BSD City. Fully furnished dengan interior modern elegan, view kolam renang. Fasilitas lengkap: pool, gym, dan akses langsung ke area komersial Sunburst BSD. Dekat AEON Mall BSD, ICE BSD, dan berbagai kantor multinasional.",
      en: "Exclusive 1-bedroom unit at Roseville SOHO & Suite, a premium apartment in the heart of BSD City. Fully furnished with modern elegant interior, pool view. Complete facilities: pool, gym, and direct access to Sunburst BSD commercial area. Near AEON Mall BSD, ICE BSD, and various multinational offices.",
    },
    ownerName: "Nita Rahayu",
    ownerPhone: "628118696940",
    ownerAvatar: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=100&q=80",
    rating: 4.8,
    reviews: 31,
    featured: true,
    verified: true,
    available: true,
    tags: ["BSD City", "Pool View", "AEON Dekat", "Premium"],
    createdAt: "2024-02-10",
  },
  {
    id: "9",
    title: "Branz BSD – 2BR Smart Living Serpong",
    slug: "branz-bsd-2br-serpong",
    location: "Jl. BSD Raya Utama, Pagedangan – Tangerang Selatan",
    city: "tangerang",
    type: "2br",
    price: 8500000,
    priceUnit: "bulan",
    size: 58,
    floor: 14,
    totalFloors: 30,
    bedrooms: 2,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80",
      "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "balcony"],
    description: {
      id: "Unit 2BR di Branz BSD, apartemen modern berkonsep smart living di kawasan BSD City Tangerang. Fully furnished dengan smart home system, AC Panasonic inverter, balkon dengan view kota. Fasilitas bintang 5: infinity pool, sky lounge, gym modern, dan co-working space. Dekat tol JORR 2 dan akses BSD - Jakarta.",
      en: "2BR unit at Branz BSD, a modern smart living concept apartment in BSD City Tangerang. Fully furnished with smart home system, Panasonic inverter AC, balcony with city view. 5-star facilities: infinity pool, sky lounge, modern gym, and co-working space. Near JORR 2 toll and BSD-Jakarta access.",
    },
    ownerName: "Reza Firmansyah",
    ownerPhone: "628118696940",
    ownerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    rating: 4.7,
    reviews: 24,
    featured: true,
    verified: true,
    available: true,
    tags: ["Smart Living", "BSD", "Sky Pool", "Balkon"],
    createdAt: "2024-01-18",
  },
  {
    id: "10",
    title: "Casa de Parco BSD – 2BR Family Pool View",
    slug: "casa-de-parco-bsd-2br-pool-view",
    location: "Jl. BSD Raya Barat, Grand Prix – BSD City Tangerang Selatan",
    city: "tangerang",
    type: "2br",
    price: 7200000,
    priceUnit: "bulan",
    size: 53,
    floor: 7,
    totalFloors: 18,
    bedrooms: 2,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80",
      "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=800&q=80",
      "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "pet"],
    description: {
      id: "Unit 2BR family di Casa de Parco BSD dengan pemandangan kolam renang yang memukau. Fully furnished lengkap dan nyaman untuk keluarga. Kompleks apartemen hijau dengan taman luas, jogging track, kolam renang dewasa & anak, dan playground. Dekat AEON Mall BSD, Green Office Park, dan sekolah internasional.",
      en: "2BR family unit at Casa de Parco BSD with stunning pool view. Fully furnished, comfortable for families. Green apartment complex with extensive gardens, jogging track, adult & children's swimming pool, and playground. Near AEON Mall BSD, Green Office Park, and international schools.",
    },
    ownerName: "Indah Permata",
    ownerPhone: "628118696940",
    ownerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    rating: 4.6,
    reviews: 18,
    featured: false,
    verified: true,
    available: true,
    tags: ["Pool View", "Family", "Pet Friendly", "BSD Green"],
    createdAt: "2024-02-28",
  },
  {
    id: "11",
    title: "Aeropolis Residence – Studio Dekat Bandara Soetta",
    slug: "aeropolis-residence-studio-bandara",
    location: "Jl. Perimeter Selatan, Neglasari – Tangerang Kota",
    city: "tangerang",
    type: "studio",
    price: 2200000,
    priceUnit: "bulan",
    size: 22,
    floor: 6,
    totalFloors: 16,
    bedrooms: 0,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80",
      "https://images.unsplash.com/photo-1505873242700-f289a29e1724?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "security", "furnished", "elevator", "laundry"],
    description: {
      id: "Studio strategis di Aeropolis Residence, hanya 5 menit dari Bandara Internasional Soekarno-Hatta. Cocok untuk pilot, pramugari, atau pekerja bandara. Fully furnished: AC, TV, springbed, lemari. Fasilitas keamanan 24 jam, shuttle bus ke terminal bandara.",
      en: "Strategic studio at Aeropolis Residence, only 5 minutes from Soekarno-Hatta International Airport. Perfect for pilots, flight attendants, or airport workers. Fully furnished: AC, TV, spring bed, wardrobe. 24-hour security, shuttle bus to airport terminal.",
    },
    ownerName: "Tono Santoso",
    ownerPhone: "628118696940",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    rating: 4.3,
    reviews: 15,
    featured: false,
    verified: true,
    available: true,
    tags: ["Dekat Bandara", "Shuttle Bus", "Budget", "Strategic"],
    createdAt: "2024-03-12",
  },

  // ── BEKASI ────────────────────────────────────────────────────────────
  {
    id: "12",
    title: "Summarecon Bekasi – 2BR Grand Orion Tower",
    slug: "summarecon-bekasi-2br-grand-orion",
    location: "Jl. Bulevar Ahmad Yani, Summarecon – Bekasi",
    city: "bekasi",
    type: "2br",
    price: 5200000,
    priceUnit: "bulan",
    size: 55,
    floor: 10,
    totalFloors: 22,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking"],
    description: {
      id: "Unit 2BR modern di Summarecon Bekasi Grand Orion Tower. Fully furnished dengan 2 AC, 2 springbed, sofa, meja makan, dan dapur lengkap. Fasilitas resort: kolam renang, gym, taman luas. Dekat Summarecon Mall Bekasi, RS Mitra Keluarga, sekolah internasional, dan akses Tol Jakarta–Bekasi.",
      en: "Modern 2BR unit at Summarecon Bekasi Grand Orion Tower. Fully furnished with 2 ACs, 2 spring beds, sofa, dining table, and complete kitchen. Resort facilities: swimming pool, gym, extensive gardens. Near Summarecon Mall Bekasi, Mitra Keluarga Hospital, international schools, and Jakarta-Bekasi toll access.",
    },
    ownerName: "Lisa Permata Sari",
    ownerPhone: "628118696940",
    ownerAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&q=80",
    rating: 4.6,
    reviews: 29,
    featured: true,
    verified: true,
    available: true,
    tags: ["Dekat Mall", "Family", "Summarecon", "Resort"],
    createdAt: "2024-02-20",
  },
  {
    id: "13",
    title: "Transpark Cibubur – Studio Dekat LRT",
    slug: "transpark-cibubur-studio-dekat-lrt",
    location: "Jl. Alternatif Cibubur, Ciracas – Jakarta Timur / Bekasi",
    city: "bekasi",
    type: "studio",
    price: 2600000,
    priceUnit: "bulan",
    size: 24,
    floor: 12,
    totalFloors: 25,
    bedrooms: 0,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "security", "furnished", "elevator"],
    description: {
      id: "Studio nyaman di Transpark Cibubur, integrated dengan pusat perbelanjaan langsung dalam satu gedung. Dekat Stasiun LRT Harjamukti dan tol Jagorawi. Fully furnished: AC, TV, springbed. Fasilitas kolam renang, jogging track, playground anak. Cocok untuk pekerja commuter atau mahasiswa.",
      en: "Comfortable studio at Transpark Cibubur, integrated with a shopping center directly in one building. Near LRT Harjamukti Station and Jagorawi toll. Fully furnished: AC, TV, spring bed. Swimming pool, jogging track, children's playground facilities. Suitable for commuter workers or students.",
    },
    ownerName: "Wahyu Nugroho",
    ownerPhone: "628118696940",
    ownerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
    rating: 4.4,
    reviews: 20,
    featured: false,
    verified: false,
    available: true,
    tags: ["Dekat LRT", "Integrated Mall", "Budget", "Commuter"],
    createdAt: "2024-03-08",
  },

  // ── DEPOK ─────────────────────────────────────────────────────────────
  {
    id: "14",
    title: "Margonda Residence 5 – Studio Dekat UI & D'Mall",
    slug: "margonda-residence-5-studio-ui",
    location: "Jl. Margonda Raya Kav. 462–465, Beji – Depok",
    city: "depok",
    type: "studio",
    price: 1900000,
    priceUnit: "bulan",
    size: 21,
    floor: 8,
    totalFloors: 18,
    bedrooms: 0,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1505873242700-f289a29e1724?w=800&q=80",
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "security", "laundry", "elevator"],
    description: {
      id: "Studio terjangkau di Margonda Residence 5, terintegrasi dengan D'Mall Depok. Hanya 10 menit berjalan kaki ke Stasiun Depok Baru dan Universitas Indonesia. Pilihan terbaik untuk mahasiswa UI, Gunadarma, dan Universitas Pancasila. Sudah termasuk biaya listrik dan air.",
      en: "Affordable studio at Margonda Residence 5, integrated with D'Mall Depok. Only 10 minutes walk to Depok Baru Station and University of Indonesia. Best choice for UI, Gunadarma, and Pancasila University students. Electricity and water bills included.",
    },
    ownerName: "Siti Nurhaliza",
    ownerPhone: "628118696940",
    ownerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
    rating: 4.4,
    reviews: 38,
    featured: false,
    verified: true,
    available: true,
    tags: ["Dekat UI", "Student Friendly", "Termurah", "D'Mall"],
    createdAt: "2024-03-05",
  },
  {
    id: "15",
    title: "Bogor Icon – 1BR Kota Hujan Premium",
    slug: "bogor-icon-1br-kota-hujan",
    location: "Jl. Pajajaran No.1, Bantarjati – Bogor Utara",
    city: "bogor",
    type: "1br",
    price: 3800000,
    priceUnit: "bulan",
    size: 36,
    floor: 11,
    totalFloors: 25,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
      "https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "security", "furnished", "elevator", "parking"],
    description: {
      id: "Unit 1BR premium di Bogor Icon, landmark baru kota Bogor. Fully furnished dengan view Gunung Salak dan Gunung Gede yang memukau. Fasilitas modern: kolam renang, keamanan 24 jam. Dekat Stasiun Bogor KRL, Kebun Raya Bogor, Botani Square Mall, dan akses Tol Jagorawi.",
      en: "Premium 1BR unit at Bogor Icon, Bogor city's new landmark. Fully furnished with stunning views of Mount Salak and Mount Gede. Modern facilities: swimming pool, 24-hour security. Near Bogor KRL Station, Bogor Botanical Garden, Botani Square Mall, and Jagorawi Toll access.",
    },
    ownerName: "Dian Purnama",
    ownerPhone: "628118696940",
    ownerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    rating: 4.5,
    reviews: 17,
    featured: false,
    verified: true,
    available: true,
    tags: ["Mountain View", "Dekat KRL", "Botani Square", "Bogor"],
    createdAt: "2024-02-25",
  },
  {
    id: "16",
    title: "Bintaro Plaza Residences – 2BR Gateway Selatan",
    slug: "bintaro-plaza-residences-2br",
    location: "Jl. Bintaro Utama Sektor 3A, Bintaro – Tangerang Selatan",
    city: "tangerang",
    type: "2br",
    price: 6800000,
    priceUnit: "bulan",
    size: 60,
    floor: 16,
    totalFloors: 28,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
      "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=800&q=80",
      "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "pool", "gym", "security", "furnished", "elevator", "parking", "balcony"],
    description: {
      id: "Unit 2BR di Bintaro Plaza Residences, terintegrasi langsung dengan Bintaro Exchange Mall. Fully furnished premium dengan balkon. Fasilitas lengkap: kolam renang, gym, jogging track. Dekat RS Internasional Bintaro, Swiss German University, dan akses tol Ulujami. Cocok untuk profesional dan keluarga yang menginginkan hunian terintegrasi kota mandiri.",
      en: "2BR unit at Bintaro Plaza Residences, directly integrated with Bintaro Exchange Mall. Premium fully furnished with balcony. Complete facilities: swimming pool, gym, jogging track. Near Bintaro International Hospital, Swiss German University, and Ulujami toll access. Suitable for professionals and families wanting an integrated self-contained city residence.",
    },
    ownerName: "Farid Wajdi",
    ownerPhone: "628118696940",
    ownerAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&q=80",
    rating: 4.7,
    reviews: 33,
    featured: true,
    verified: true,
    available: true,
    tags: ["Integrated Mall", "Bintaro", "Balkon", "Premium"],
    createdAt: "2024-01-30",
  },
];

export const STATS = [
  { value: 2940, suffix: "+", label: { id: "Listing Aktif", en: "Active Listings" } },
  { value: 5, suffix: " Kota", label: { id: "Area JABODETABEK", en: "JABODETABEK Areas" } },
  { value: 12500, suffix: "+", label: { id: "Penyewa Puas", en: "Happy Tenants" } },
  { value: 98, suffix: "%", label: { id: "Tingkat Kepuasan", en: "Satisfaction Rate" } },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Andi Wijaksono",
    role: { id: "Software Engineer, Jakarta", en: "Software Engineer, Jakarta" },
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
    rating: 5,
    text: {
      id: "SewaApartement benar-benar memudahkan saya menemukan apartemen yang tepat. Dalam waktu 3 hari langsung dapat unit Branz Simatupang yang sesuai budget. Prosesnya mudah dan langsung bisa contact owner via WhatsApp!",
      en: "SewaApartement really made it easy for me to find the right apartment. Within 3 days I got a Branz Simatupang unit that fits my budget. The process is easy and I can directly contact the owner via WhatsApp!",
    },
  },
  {
    id: 2,
    name: "Maya Pertiwi",
    role: { id: "Mahasiswi UI, Depok", en: "UI Student, Depok" },
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
    rating: 5,
    text: {
      id: "Sebagai mahasiswi baru di Depok, saya sangat terbantu. Nemu Margonda Residence 5 yang harganya super terjangkau dan dekat banget sama kampus UI. Langsung chat WhatsApp pemilik, deal dalam sehari!",
      en: "As a new student in Depok, I was greatly helped. Found Margonda Residence 5 at a super affordable price and very close to UI campus. Directly WhatsApp chatted with the owner, deal in one day!",
    },
  },
  {
    id: 3,
    name: "Budi Kurniawan",
    role: { id: "Pemilik Apartemen, BSD", en: "Apartment Owner, BSD" },
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    rating: 5,
    text: {
      id: "Saya sudah daftarkan 2 unit di Roseville BSD dan Casa de Parco. Dalam seminggu langsung ada yang menghubungi via WhatsApp. Dashboard pemilik sangat mudah digunakan untuk manage listing.",
      en: "I have registered 2 units at Roseville BSD and Casa de Parco. Within a week there were already inquiries via WhatsApp. The owner dashboard is very easy to use to manage listings.",
    },
  },
  {
    id: 4,
    name: "Sarah Chen",
    role: { id: "Ekspatriat, SCBD Jakarta", en: "Expat, SCBD Jakarta" },
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    rating: 5,
    text: {
      id: "Fitur bilingual sangat membantu saya sebagai ekspatriat. Informasi Anandamaya Residence jelas dan lengkap. Bisa langsung WhatsApp owner tanpa perantara. Found my dream apartment here!",
      en: "The bilingual feature really helps me as an expat. Anandamaya Residence information is clear and complete. Can directly WhatsApp the owner without intermediaries. Found my dream apartment here!",
    },
  },
];

export const HOW_IT_WORKS_TENANT = [
  {
    step: 1,
    icon: "🔍",
    title: { id: "Cari Apartemen", en: "Search Apartment" },
    desc: { id: "Gunakan filter kota, harga, tipe, dan fasilitas untuk menemukan apartemen yang sesuai kebutuhan.", en: "Use city, price, type, and amenity filters to find the apartment that suits your needs." },
  },
  {
    step: 2,
    icon: "👀",
    title: { id: "Lihat Detail", en: "View Details" },
    desc: { id: "Cek foto lengkap, fasilitas, lokasi di peta, dan semua informasi yang Anda butuhkan.", en: "Check complete photos, amenities, location on the map, and all the information you need." },
  },
  {
    step: 3,
    icon: "💬",
    title: { id: "Hubungi Pemilik", en: "Contact Owner" },
    desc: { id: "Langsung hubungi pemilik via WhatsApp untuk negosiasi harga dan jadwal survei.", en: "Directly contact the owner via WhatsApp to negotiate prices and schedule a survey." },
  },
  {
    step: 4,
    icon: "🏠",
    title: { id: "Sewa & Tinggal", en: "Rent & Move In" },
    desc: { id: "Setelah deal dengan pemilik, langsung pindah ke apartemen impian Anda!", en: "After a deal with the owner, move directly into your dream apartment!" },
  },
];

export const HOW_IT_WORKS_OWNER = [
  {
    step: 1,
    icon: "📝",
    title: { id: "Daftar Akun", en: "Register Account" },
    desc: { id: "Buat akun pemilik gratis dalam hitungan menit. Verifikasi identitas untuk meningkatkan kepercayaan.", en: "Create a free owner account in minutes. Verify identity to increase trust." },
  },
  {
    step: 2,
    icon: "📸",
    title: { id: "Upload Listing", en: "Upload Listing" },
    desc: { id: "Upload foto properti, isi detail lengkap, tentukan harga, dan pilih fasilitas yang tersedia.", en: "Upload property photos, fill in complete details, set prices, and select available amenities." },
  },
  {
    step: 3,
    icon: "✅",
    title: { id: "Listing Aktif", en: "Listing Active" },
    desc: { id: "Listing Anda akan langsung aktif dan terlihat oleh ribuan pencari apartemen.", en: "Your listing will be immediately active and visible to thousands of apartment seekers." },
  },
  {
    step: 4,
    icon: "📞",
    title: { id: "Terima Calon Penyewa", en: "Receive Tenants" },
    desc: { id: "Calon penyewa akan menghubungi langsung via WhatsApp yang Anda daftarkan.", en: "Prospective tenants will contact you directly via WhatsApp that you registered." },
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    slug: "tips-sewa-apartemen-jakarta-pertama-kali",
    title: { id: "10 Tips Sewa Apartemen di Jakarta untuk Pertama Kali", en: "10 Tips for Renting an Apartment in Jakarta for the First Time" },
    excerpt: { id: "Menyewa apartemen pertama kali di Jakarta bisa terasa membingungkan. Berikut panduan lengkap agar Anda tidak salah pilih.", en: "Renting an apartment for the first time in Jakarta can feel confusing. Here is a complete guide so you don't make the wrong choice." },
    category: { id: "Panduan", en: "Guide" },
    image: "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=600&q=80",
    author: "Tim Redaksi",
    date: "2024-03-01",
    readTime: 7,
  },
  {
    id: 2,
    slug: "perbandingan-harga-apartemen-jabodetabek-2024",
    title: { id: "Perbandingan Harga Apartemen JABODETABEK 2024", en: "JABODETABEK Apartment Price Comparison 2024" },
    excerpt: { id: "Analisis lengkap harga sewa apartemen di Jakarta, Bogor, Depok, Tangerang, dan Bekasi. Mana yang paling terjangkau?", en: "Complete analysis of apartment rental prices in Jakarta, Bogor, Depok, Tangerang, and Bekasi. Which is the most affordable?" },
    category: { id: "Analisis Pasar", en: "Market Analysis" },
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80",
    author: "Analis Properti",
    date: "2024-02-20",
    readTime: 10,
  },
  {
    id: 3,
    slug: "apartemen-terbaik-untuk-mahasiswa-depok",
    title: { id: "Rekomendasi Apartemen Terbaik untuk Mahasiswa di Depok", en: "Best Apartment Recommendations for Students in Depok" },
    excerpt: { id: "Daftar apartemen terbaik di Depok dengan harga ramah mahasiswa, lengkap dengan fasilitas dan akses transportasi.", en: "List of the best apartments in Depok with student-friendly prices, complete with facilities and transportation access." },
    category: { id: "Rekomendasi", en: "Recommendation" },
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    author: "Tim Redaksi",
    date: "2024-02-10",
    readTime: 5,
  },
];

export const FAQS = [
  {
    q: { id: "Apakah pendaftaran sebagai pemilik gratis?", en: "Is registration as an owner free?" },
    a: { id: "Ya, pendaftaran dan upload listing pertama Anda sepenuhnya gratis. Nikmati layanan dasar tanpa biaya apapun.", en: "Yes, registration and uploading your first listing is completely free. Enjoy basic services at no cost." },
  },
  {
    q: { id: "Bagaimana cara calon penyewa menghubungi saya?", en: "How do potential tenants contact me?" },
    a: { id: "Calon penyewa akan langsung menghubungi Anda melalui nomor WhatsApp yang Anda daftarkan di profil dan listing.", en: "Potential tenants will directly contact you through the WhatsApp number you registered in your profile and listing." },
  },
  {
    q: { id: "Apakah ada proses verifikasi untuk listing?", en: "Is there a verification process for listings?" },
    a: { id: "Ya, tim kami melakukan verifikasi dasar untuk memastikan keaslian listing. Pemilik yang terverifikasi mendapat badge khusus.", en: "Yes, our team does basic verification to ensure the authenticity of listings. Verified owners get a special badge." },
  },
  {
    q: { id: "Berapa lama listing saya aktif?", en: "How long will my listing be active?" },
    a: { id: "Listing aktif selama 90 hari dan dapat diperpanjang kapan saja melalui dashboard pemilik.", en: "Listings are active for 90 days and can be renewed at any time through the owner dashboard." },
  },
  {
    q: { id: "Apakah platform ini aman?", en: "Is this platform safe?" },
    a: { id: "Keamanan adalah prioritas kami. Semua pengguna terverifikasi, dan kami memiliki sistem pelaporan untuk konten yang mencurigakan.", en: "Security is our priority. All users are verified, and we have a reporting system for suspicious content." },
  },
];

export const formatPrice = (price: number): string => {
  if (price >= 1000000) {
    const val = price / 1000000;
    return `Rp ${val % 1 === 0 ? val.toFixed(0) : val.toFixed(1)} Jt`;
  }
  return `Rp ${price.toLocaleString("id-ID")}`;
};
