export const SITE_NAME = "SewaTerlengkap";
export const SITE_TAGLINE = {
  id: "Platform Sewa Apartemen #1 di JABODETABEK",
  en: "The #1 Apartment Rental Platform in JABODETABEK",
};
export const SITE_DESC = {
  id: "Temukan apartemen impian Anda di Jakarta, Bogor, Depok, Tangerang, dan Bekasi. Ribuan pilihan untuk mahasiswa, pekerja, dan keluarga.",
  en: "Find your dream apartment in Jakarta, Bogor, Depok, Tangerang, and Bekasi. Thousands of options for students, workers, and families.",
};

export const CITIES = [
  { id: "jakarta", name: "Jakarta", icon: "🏙️", count: 1240 },
  { id: "bogor", name: "Bogor", icon: "🌿", count: 320 },
  { id: "depok", name: "Depok", icon: "🏫", count: 410 },
  { id: "tangerang", name: "Tangerang", icon: "✈️", count: 580 },
  { id: "bekasi", name: "Bekasi", icon: "🏭", count: 390 },
];

export const APARTMENT_TYPES = [
  { id: "studio", label: { id: "Studio", en: "Studio" } },
  { id: "1br", label: { id: "1 Kamar", en: "1 Bedroom" } },
  { id: "2br", label: { id: "2 Kamar", en: "2 Bedrooms" } },
  { id: "3br", label: { id: "3 Kamar", en: "3 Bedrooms" } },
  { id: "penthouse", label: { id: "Penthouse", en: "Penthouse" } },
];

export const RENT_DURATIONS = [
  { id: "harian", label: { id: "Harian", en: "Daily" } },
  { id: "bulanan", label: { id: "Bulanan", en: "Monthly" } },
  { id: "tahunan", label: { id: "Tahunan", en: "Yearly" } },
];

export const PRICE_RANGES = [
  { id: "0-1jt", label: { id: "< Rp 1 Juta/bln", en: "< Rp 1M/month" }, min: 0, max: 1000000 },
  { id: "1-3jt", label: { id: "Rp 1–3 Juta/bln", en: "Rp 1–3M/month" }, min: 1000000, max: 3000000 },
  { id: "3-5jt", label: { id: "Rp 3–5 Juta/bln", en: "Rp 3–5M/month" }, min: 3000000, max: 5000000 },
  { id: "5-10jt", label: { id: "Rp 5–10 Juta/bln", en: "Rp 5–10M/month" }, min: 5000000, max: 10000000 },
  { id: "10jt+", label: { id: "> Rp 10 Juta/bln", en: "> Rp 10M/month" }, min: 10000000, max: 999999999 },
];

export const AMENITIES = [
  { id: "wifi", icon: "📶", label: { id: "WiFi", en: "WiFi" } },
  { id: "ac", icon: "❄️", label: { id: "AC", en: "AC" } },
  { id: "parking", icon: "🚗", label: { id: "Parkir", en: "Parking" } },
  { id: "pool", icon: "🏊", label: { id: "Kolam Renang", en: "Pool" } },
  { id: "gym", icon: "🏋️", label: { id: "Gym", en: "Gym" } },
  { id: "security", icon: "🔒", label: { id: "Keamanan 24 Jam", en: "24H Security" } },
  { id: "laundry", icon: "👕", label: { id: "Laundry", en: "Laundry" } },
  { id: "kitchen", icon: "🍳", label: { id: "Dapur", en: "Kitchen" } },
  { id: "balcony", icon: "🌅", label: { id: "Balkon", en: "Balcony" } },
  { id: "pet", icon: "🐾", label: { id: "Pet Friendly", en: "Pet Friendly" } },
  { id: "furnished", icon: "🛋️", label: { id: "Fully Furnished", en: "Fully Furnished" } },
  { id: "elevator", icon: "🛗", label: { id: "Lift", en: "Elevator" } },
];

export const SAMPLE_LISTINGS = [
  {
    id: "1",
    title: "Apartemen Premium Sudirman Tower A",
    slug: "apartemen-premium-sudirman-tower-a",
    location: "Sudirman, Jakarta Selatan",
    city: "jakarta",
    type: "2br",
    price: 7500000,
    priceUnit: "bulan",
    size: 65,
    floor: 28,
    totalFloors: 45,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "parking", "pool", "gym", "security", "furnished", "elevator", "balcony"],
    description: {
      id: "Unit premium di lantai tinggi dengan view kota Jakarta yang menakjubkan. Fully furnished dengan furnitur mewah, dapur modern, dan akses langsung ke fasilitas bintang 5 termasuk rooftop pool dan private gym.",
      en: "Premium unit on high floor with stunning Jakarta city views. Fully furnished with luxury furniture, modern kitchen, and direct access to 5-star facilities including rooftop pool and private gym.",
    },
    ownerName: "Budi Santoso",
    ownerPhone: "628123456789",
    ownerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    rating: 4.9,
    reviews: 47,
    featured: true,
    verified: true,
    available: true,
    tags: ["Furnished", "Pool", "Gym", "Pet Friendly"],
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    title: "Studio Modern Dekat MRT Fatmawati",
    slug: "studio-modern-mrt-fatmawati",
    location: "Fatmawati, Jakarta Selatan",
    city: "jakarta",
    type: "studio",
    price: 3200000,
    priceUnit: "bulan",
    size: 28,
    floor: 12,
    totalFloors: 30,
    bedrooms: 0,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80",
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "security", "laundry", "furnished", "elevator"],
    description: {
      id: "Studio modern strategis 5 menit jalan kaki ke Stasiun MRT Fatmawati. Cocok untuk profesional muda. Unit fully furnished dengan smart TV dan high-speed internet.",
      en: "Modern studio strategically located 5 minutes walking to MRT Fatmawati Station. Perfect for young professionals. Fully furnished unit with smart TV and high-speed internet.",
    },
    ownerName: "Dewi Rahayu",
    ownerPhone: "628234567890",
    ownerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    rating: 4.7,
    reviews: 23,
    featured: true,
    verified: true,
    available: true,
    tags: ["MRT Dekat", "Furnished", "Cozy"],
    createdAt: "2024-02-10",
  },
  {
    id: "3",
    title: "Apartemen Keluarga Green Garden BSD",
    slug: "apartemen-keluarga-green-garden-bsd",
    location: "BSD City, Tangerang Selatan",
    city: "tangerang",
    type: "3br",
    price: 9800000,
    priceUnit: "bulan",
    size: 95,
    floor: 8,
    totalFloors: 20,
    bedrooms: 3,
    bathrooms: 2,
    images: [
      "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80",
      "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80",
      "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "parking", "pool", "security", "furnished", "elevator", "pet", "balcony"],
    description: {
      id: "Apartemen keluarga luas di kawasan BSD yang hijau dan nyaman. 3 kamar tidur, 2 kamar mandi, ruang keluarga besar. Dekat mall, sekolah internasional, dan akses tol mudah.",
      en: "Spacious family apartment in the green and comfortable BSD area. 3 bedrooms, 2 bathrooms, large living room. Near mall, international schools, and easy toll access.",
    },
    ownerName: "Ahmad Fauzi",
    ownerPhone: "628345678901",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    rating: 4.8,
    reviews: 31,
    featured: true,
    verified: true,
    available: true,
    tags: ["Family", "Pet Friendly", "Garden View"],
    createdAt: "2024-01-28",
  },
  {
    id: "4",
    title: "Studio Mahasiswa Dekat UI Depok",
    slug: "studio-mahasiswa-dekat-ui-depok",
    location: "Beji, Depok",
    city: "depok",
    type: "studio",
    price: 1800000,
    priceUnit: "bulan",
    size: 22,
    floor: 5,
    totalFloors: 15,
    bedrooms: 0,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80",
      "https://images.unsplash.com/photo-1505873242700-f289a29e1724?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "security", "laundry"],
    description: {
      id: "Studio terjangkau dan strategis untuk mahasiswa UI. 10 menit ke kampus. Sudah include tagihan listrik dan air. Lingkungan aman dan tenang.",
      en: "Affordable and strategic studio for UI students. 10 minutes to campus. Already includes electricity and water bills. Safe and quiet environment.",
    },
    ownerName: "Siti Nurhaliza",
    ownerPhone: "628456789012",
    ownerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
    rating: 4.5,
    reviews: 18,
    featured: false,
    verified: true,
    available: true,
    tags: ["Student Friendly", "Budget", "Near Campus"],
    createdAt: "2024-03-05",
  },
  {
    id: "5",
    title: "1BR Eksklusif Kelapa Gading",
    slug: "1br-eksklusif-kelapa-gading",
    location: "Kelapa Gading, Jakarta Utara",
    city: "jakarta",
    type: "1br",
    price: 5500000,
    priceUnit: "bulan",
    size: 42,
    floor: 18,
    totalFloors: 35,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800&q=80",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
      "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "parking", "pool", "gym", "security", "furnished", "elevator", "balcony"],
    description: {
      id: "Unit 1 bedroom eksklusif di jantung Kelapa Gading. Interior modern minimalis, view skyline Jakarta, akses langsung ke mal Kelapa Gading. Cocok untuk profesional ekspatriat.",
      en: "Exclusive 1 bedroom unit in the heart of Kelapa Gading. Modern minimalist interior, Jakarta skyline view, direct access to Kelapa Gading mall. Perfect for expat professionals.",
    },
    ownerName: "Robert Wijaya",
    ownerPhone: "628567890123",
    ownerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
    rating: 4.9,
    reviews: 56,
    featured: true,
    verified: true,
    available: true,
    tags: ["Luxury", "City View", "Expat Friendly"],
    createdAt: "2024-01-05",
  },
  {
    id: "6",
    title: "2BR Nyaman Summarecon Bekasi",
    slug: "2br-summarecon-bekasi",
    location: "Summarecon, Bekasi",
    city: "bekasi",
    type: "2br",
    price: 4800000,
    priceUnit: "bulan",
    size: 55,
    floor: 6,
    totalFloors: 18,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "parking", "pool", "security", "furnished", "elevator"],
    description: {
      id: "Apartemen 2 kamar yang luas dan nyaman di kawasan Summarecon Bekasi. Dekat dengan pusat perbelanjaan, restoran, dan akses tol Jakarta-Bekasi. Cocok untuk pasangan dan keluarga kecil.",
      en: "Spacious and comfortable 2-bedroom apartment in Summarecon Bekasi area. Close to shopping centers, restaurants, and Jakarta-Bekasi toll access. Perfect for couples and small families.",
    },
    ownerName: "Lisa Permata",
    ownerPhone: "628678901234",
    ownerAvatar: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=100&q=80",
    rating: 4.6,
    reviews: 29,
    featured: false,
    verified: true,
    available: true,
    tags: ["Family", "Comfortable", "Near Mall"],
    createdAt: "2024-02-20",
  },
  {
    id: "7",
    title: "Penthouse Mewah Senopati Signature",
    slug: "penthouse-senopati-signature",
    location: "Senopati, Jakarta Selatan",
    city: "jakarta",
    type: "penthouse",
    price: 35000000,
    priceUnit: "bulan",
    size: 220,
    floor: 48,
    totalFloors: 50,
    bedrooms: 4,
    bathrooms: 4,
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "parking", "pool", "gym", "security", "furnished", "elevator", "balcony", "pet", "kitchen"],
    description: {
      id: "Penthouse eksklusif di lantai paling atas dengan panorama 360° Jakarta. 4 kamar tidur, private pool, dapur chef, ruang wine, dan private lift. Keamanan 24 jam dengan concierge personal.",
      en: "Exclusive penthouse on the top floor with 360° panoramic view of Jakarta. 4 bedrooms, private pool, chef's kitchen, wine room, and private lift. 24-hour security with personal concierge.",
    },
    ownerName: "Michael Hartono",
    ownerPhone: "628789012345",
    ownerAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&q=80",
    rating: 5.0,
    reviews: 12,
    featured: true,
    verified: true,
    available: true,
    tags: ["Penthouse", "Luxury", "360° View", "Private Pool"],
    createdAt: "2024-01-01",
  },
  {
    id: "8",
    title: "Studio Cozy Margonda Raya Depok",
    slug: "studio-cozy-margonda-depok",
    location: "Margonda, Depok",
    city: "depok",
    type: "studio",
    price: 2500000,
    priceUnit: "bulan",
    size: 26,
    floor: 9,
    totalFloors: 22,
    bedrooms: 0,
    bathrooms: 1,
    images: [
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    amenities: ["wifi", "ac", "security", "laundry", "furnished"],
    description: {
      id: "Studio cozy di jantung Margonda. Dekat Universitas Indonesia dan Gunadarma. Akses mudah ke Stasiun Depok. Cocok untuk mahasiswa dan pekerja.",
      en: "Cozy studio in the heart of Margonda. Near University of Indonesia and Gunadarma. Easy access to Depok Station. Perfect for students and workers.",
    },
    ownerName: "Rini Susanti",
    ownerPhone: "628890123456",
    ownerAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&q=80",
    rating: 4.4,
    reviews: 21,
    featured: false,
    verified: false,
    available: true,
    tags: ["Student", "Cozy", "Strategic"],
    createdAt: "2024-03-15",
  },
];

export const STATS = [
  { value: 2940, suffix: "+", label: { id: "Listing Aktif", en: "Active Listings" } },
  { value: 5, suffix: " Kota", label: { id: "Area JABODETABEK", en: "JABODETABEK Areas" } },
  { value: 12500, suffix: "+", label: { id: "Penyewa Puas", en: "Happy Tenants" } },
  { value: 98, suffix: "%", label: { id: "Tingkat Kepuasan", en: "Satisfaction Rate" } },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Andi Wijaksono",
    role: { id: "Software Engineer, Jakarta", en: "Software Engineer, Jakarta" },
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
    rating: 5,
    text: {
      id: "SewaTerlengkap benar-benar memudahkan saya menemukan apartemen yang tepat. Dalam waktu 3 hari langsung dapat unit yang sesuai budget di Sudirman. Prosesnya mudah dan langsung bisa contact owner!",
      en: "SewaTerlengkap really made it easy for me to find the right apartment. Within 3 days I got a unit that fits my budget in Sudirman. The process is easy and I can directly contact the owner!",
    },
  },
  {
    id: 2,
    name: "Maya Pertiwi",
    role: { id: "Mahasiswi UI, Depok", en: "UI Student, Depok" },
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
    rating: 5,
    text: {
      id: "Sebagai mahasiswi baru di Jakarta, saya sangat terbantu dengan filter harga dan lokasi. Bisa langsung chat lewat WhatsApp dengan pemilik. Sangat recommended!",
      en: "As a new student in Jakarta, I was greatly helped by the price and location filters. Can directly chat via WhatsApp with the owner. Highly recommended!",
    },
  },
  {
    id: 3,
    name: "Budi Kurniawan",
    role: { id: "Pemilik Apartemen, BSD", en: "Apartment Owner, BSD" },
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    rating: 5,
    text: {
      id: "Saya sudah daftarkan 3 unit apartemen di SewaTerlengkap. Dalam seminggu langsung ada yang menghubungi. Dashboard pemilik sangat mudah digunakan untuk manage listing.",
      en: "I have registered 3 apartment units on SewaTerlengkap. Within a week there were already inquiries. The owner dashboard is very easy to use to manage listings.",
    },
  },
  {
    id: 4,
    name: "Sarah Chen",
    role: { id: "Ekspatriat, Kelapa Gading", en: "Expat, Kelapa Gading" },
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    rating: 5,
    text: {
      id: "Fitur bilingual sangat membantu saya sebagai ekspatriat. Informasi properti jelas, foto lengkap, dan kontak pemilik mudah dihubungi. Found my dream apartment here!",
      en: "The bilingual feature really helps me as an expat. Property information is clear, photos are complete, and the owner's contact is easy to reach. Found my dream apartment here!",
    },
  },
];

export const HOW_IT_WORKS_TENANT = [
  {
    step: 1,
    icon: "🔍",
    title: { id: "Cari Apartemen", en: "Search Apartment" },
    desc: { id: "Gunakan filter kota, harga, tipe, dan fasilitas untuk menemukan apartemen yang sesuai kebutuhan.", en: "Use city, price, type, and amenity filters to find the apartment that suits your needs." },
  },
  {
    step: 2,
    icon: "👀",
    title: { id: "Lihat Detail", en: "View Details" },
    desc: { id: "Cek foto lengkap, fasilitas, lokasi di peta, dan semua informasi yang Anda butuhkan.", en: "Check complete photos, amenities, location on the map, and all the information you need." },
  },
  {
    step: 3,
    icon: "💬",
    title: { id: "Hubungi Pemilik", en: "Contact Owner" },
    desc: { id: "Langsung hubungi pemilik via WhatsApp untuk negosiasi harga dan jadwal survei.", en: "Directly contact the owner via WhatsApp to negotiate prices and schedule a survey." },
  },
  {
    step: 4,
    icon: "🏠",
    title: { id: "Sewa & Tinggal", en: "Rent & Move In" },
    desc: { id: "Setelah deal dengan pemilik, langsung pindah ke apartemen impian Anda!", en: "After a deal with the owner, move directly into your dream apartment!" },
  },
];

export const HOW_IT_WORKS_OWNER = [
  {
    step: 1,
    icon: "📝",
    title: { id: "Daftar Akun", en: "Register Account" },
    desc: { id: "Buat akun pemilik gratis dalam hitungan menit. Verifikasi identitas untuk meningkatkan kepercayaan.", en: "Create a free owner account in minutes. Verify identity to increase trust." },
  },
  {
    step: 2,
    icon: "📸",
    title: { id: "Upload Listing", en: "Upload Listing" },
    desc: { id: "Upload foto properti, isi detail lengkap, tentukan harga, dan pilih fasilitas yang tersedia.", en: "Upload property photos, fill in complete details, set prices, and select available amenities." },
  },
  {
    step: 3,
    icon: "✅",
    title: { id: "Listing Aktif", en: "Listing Active" },
    desc: { id: "Listing Anda akan langsung aktif dan terlihat oleh ribuan pencari apartemen.", en: "Your listing will be immediately active and visible to thousands of apartment seekers." },
  },
  {
    step: 4,
    icon: "📞",
    title: { id: "Terima Calon Penyewa", en: "Receive Tenants" },
    desc: { id: "Calon penyewa akan menghubungi langsung via WhatsApp yang Anda daftarkan.", en: "Prospective tenants will contact you directly via WhatsApp that you registered." },
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    slug: "tips-sewa-apartemen-jakarta-pertama-kali",
    title: { id: "10 Tips Sewa Apartemen di Jakarta untuk Pertama Kali", en: "10 Tips for Renting an Apartment in Jakarta for the First Time" },
    excerpt: { id: "Menyewa apartemen pertama kali di Jakarta bisa terasa membingungkan. Berikut panduan lengkap agar Anda tidak salah pilih.", en: "Renting an apartment for the first time in Jakarta can feel confusing. Here is a complete guide so you don't make the wrong choice." },
    category: { id: "Panduan", en: "Guide" },
    image: "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=600&q=80",
    author: "Tim Redaksi",
    date: "2024-03-01",
    readTime: 7,
  },
  {
    id: 2,
    slug: "perbandingan-harga-apartemen-jabodetabek-2024",
    title: { id: "Perbandingan Harga Apartemen JABODETABEK 2024", en: "JABODETABEK Apartment Price Comparison 2024" },
    excerpt: { id: "Analisis lengkap harga sewa apartemen di Jakarta, Bogor, Depok, Tangerang, dan Bekasi. Mana yang paling terjangkau?", en: "Complete analysis of apartment rental prices in Jakarta, Bogor, Depok, Tangerang, and Bekasi. Which is the most affordable?" },
    category: { id: "Analisis Pasar", en: "Market Analysis" },
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80",
    author: "Analis Properti",
    date: "2024-02-20",
    readTime: 10,
  },
  {
    id: 3,
    slug: "apartemen-terbaik-untuk-mahasiswa-depok",
    title: { id: "Rekomendasi Apartemen Terbaik untuk Mahasiswa di Depok", en: "Best Apartment Recommendations for Students in Depok" },
    excerpt: { id: "Daftar apartemen terbaik di Depok dengan harga ramah mahasiswa, lengkap dengan fasilitas dan akses transportasi.", en: "List of the best apartments in Depok with student-friendly prices, complete with facilities and transportation access." },
    category: { id: "Rekomendasi", en: "Recommendation" },
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    author: "Tim Redaksi",
    date: "2024-02-10",
    readTime: 5,
  },
];

export const FAQS = [
  {
    q: { id: "Apakah pendaftaran sebagai pemilik gratis?", en: "Is registration as an owner free?" },
    a: { id: "Ya, pendaftaran dan upload listing pertama Anda sepenuhnya gratis. Nikmati layanan dasar tanpa biaya apapun.", en: "Yes, registration and uploading your first listing is completely free. Enjoy basic services at no cost." },
  },
  {
    q: { id: "Bagaimana cara calon penyewa menghubungi saya?", en: "How do potential tenants contact me?" },
    a: { id: "Calon penyewa akan langsung menghubungi Anda melalui nomor WhatsApp yang Anda daftarkan di profil dan listing.", en: "Potential tenants will directly contact you through the WhatsApp number you registered in your profile and listing." },
  },
  {
    q: { id: "Apakah ada proses verifikasi untuk listing?", en: "Is there a verification process for listings?" },
    a: { id: "Ya, tim kami melakukan verifikasi dasar untuk memastikan keaslian listing. Pemilik yang terverifikasi mendapat badge khusus.", en: "Yes, our team does basic verification to ensure the authenticity of listings. Verified owners get a special badge." },
  },
  {
    q: { id: "Berapa lama listing saya aktif?", en: "How long will my listing be active?" },
    a: { id: "Listing aktif selama 90 hari dan dapat diperpanjang kapan saja melalui dashboard pemilik.", en: "Listings are active for 90 days and can be renewed at any time through the owner dashboard." },
  },
  {
    q: { id: "Apakah platform ini aman?", en: "Is this platform safe?" },
    a: { id: "Keamanan adalah prioritas kami. Semua pengguna terverifikasi, dan kami memiliki sistem pelaporan untuk konten yang mencurigakan.", en: "Security is our priority. All users are verified, and we have a reporting system for suspicious content." },
  },
];

export const formatPrice = (price: number): string => {
  if (price >= 1000000) {
    return `Rp ${(price / 1000000).toFixed(1)} Jt`;
  }
  return `Rp ${price.toLocaleString("id-ID")}`;
};
