import { NextRequest, NextResponse } from "next/server";

// ─────────────────────────────────────────────────────────────────────────────
// STORAGE STRATEGY
// Vercel serverless: filesystem is READ-ONLY except /tmp (ephemeral).
// Solusi: simpan artikel baru ke GLOBAL in-memory cache (persist selama
// instance hidup) + kembalikan sebagai response agar frontend bisa simpan
// di localStorage/sessionStorage. Artikel seed permanen ada di SEED_BLOGS.
//
// Untuk persistence jangka panjang: tambahkan Vercel KV atau PlanetScale
// di masa mendatang. Saat ini tanpa setup tambahan sudah cukup untuk demo.
// ─────────────────────────────────────────────────────────────────────────────

// In-memory store (persist selama serverless instance hidup, ~hours)
declare global {
  var __blogCache: any[] | undefined;
}

function getCache(): any[] {
  if (!global.__blogCache) global.__blogCache = [];
  return global.__blogCache;
}

function addToCache(article: any) {
  const cache = getCache();
  // Hindari duplikat
  if (!cache.find((a) => a.id === article.id)) {
    cache.push(article);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Seed articles — selalu tersedia
// ─────────────────────────────────────────────────────────────────────────────
export const SEED_BLOGS = [
  {
    id: "seed-001",
    slug: "tips-sewa-apartemen-jakarta-pertama-kali",
    topicId: "tips-pertama",
    title: { id: "10 Tips Sewa Apartemen di Jakarta untuk Pertama Kali", en: "10 Tips for Renting an Apartment in Jakarta for the First Time" },
    excerpt: { id: "Menyewa apartemen pertama kali di Jakarta bisa terasa membingungkan. Berikut panduan lengkap agar tidak salah pilih.", en: "Renting an apartment for the first time in Jakarta can feel confusing. Here is a complete guide." },
    content: {
      id: `## 10 Tips Sewa Apartemen di Jakarta untuk Pertama Kali\n\nMencari apartemen pertama di Jakarta memang butuh strategi. Berikut 10 tips yang perlu Anda ketahui:\n\n### 1. Tentukan Budget Sejak Awal\nAlokasikan maksimal 30% dari penghasilan bulanan untuk sewa. Jangan lupa perhitungkan biaya IPL, listrik, air, dan internet.\n\n### 2. Pilih Lokasi Strategis\nPertimbangkan jarak ke kantor/kampus, akses MRT/KRL/TransJakarta, dan fasilitas sekitar.\n\n### 3. Pahami Apa yang Include\nTanyakan apakah harga sudah include WiFi, listrik, air, IPL, dan parkir.\n\n### 4. Cek Kondisi Unit Langsung\nMinta video call atau kunjungi langsung sebelum deal. Perhatikan kondisi AC, plumbing, dan keamanan.\n\n### 5. Baca Kontrak dengan Teliti\nPerhatikan klausul deposit (biasanya 1-2 bulan), durasi kontrak minimum.\n\n### 6. Negosiasi Harga\nHarga listing bukan harga mati. Untuk kontrak tahunan, biasanya bisa nego 5-15%.\n\n### 7. Cek Keamanan Gedung\nPastikan ada CCTV, security 24 jam, dan sistem akses kartu.\n\n### 8. Perhatikan Arah Hadap Unit\nUnit hadap timur dapat sinar pagi yang baik.\n\n### 9. Tanya Tetangga atau Review Online\nCari review apartemen di Google Maps atau forum.\n\n### 10. Gunakan Platform Terpercaya\nCari listing di **SewaApartement.id** yang sudah terverifikasi dan langsung bisa kontak pemilik via WhatsApp tanpa perantara.`,
      en: `## 10 Tips for Renting an Apartment in Jakarta\n\nFinding your first apartment in Jakarta requires strategy. Set your budget, choose a strategic location, understand what's included, and use a trusted platform like SewaApartement.id to find verified listings.`,
    },
    category: { id: "Panduan", en: "Guide" },
    tags: ["tips", "jakarta", "pertama kali", "panduan sewa"],
    image: "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&q=80",
    author: "Tim Redaksi SewaApartement",
    authorAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=60&q=80",
    publishedAt: "2024-03-01T08:00:00.000Z",
    readTime: 7,
    views: 1842,
    featured: true,
    autoGenerated: false,
  },
  {
    id: "seed-002",
    slug: "perbandingan-harga-apartemen-jabodetabek-2024",
    topicId: "harga-jabodetabek",
    title: { id: "Perbandingan Harga Sewa Apartemen JABODETABEK 2024", en: "JABODETABEK Apartment Rental Price Comparison 2024" },
    excerpt: { id: "Analisis lengkap harga sewa apartemen di Jakarta, Bogor, Depok, Tangerang, dan Bekasi. Mana yang paling terjangkau?", en: "Complete analysis of apartment rental prices across JABODETABEK." },
    content: {
      id: `## Perbandingan Harga Sewa Apartemen JABODETABEK 2024\n\nMemilih kota tempat tinggal di Jabodetabek sangat bergantung pada budget dan gaya hidup Anda.\n\n## Jakarta\n- **Studio:** Rp 2,5 – 5 juta/bulan\n- **1BR:** Rp 4 – 9 juta/bulan\n- **2BR:** Rp 6 – 20 juta/bulan\n- Area premium (SCBD, Sudirman): bisa di atas Rp 15 juta/bulan\n\n## Tangerang Selatan (BSD, Bintaro)\n- **Studio:** Rp 2 – 4 juta/bulan\n- **1BR:** Rp 4 – 7 juta/bulan\n- **2BR:** Rp 6 – 12 juta/bulan\n\n## Bekasi (Summarecon, Galaxy)\n- **Studio:** Rp 2 – 3,5 juta/bulan\n- **1BR:** Rp 3,5 – 6 juta/bulan\n- **2BR:** Rp 5 – 9 juta/bulan\n\n## Depok (Margonda)\n- **Studio:** Rp 1,5 – 3 juta/bulan (paling cocok untuk mahasiswa)\n\n## Bogor\n- **Studio:** Rp 1,5 – 3 juta/bulan\n\n### Kesimpulan\nUntuk budget di bawah Rp 3 juta → Depok dan Bogor. Budget Rp 3-7 juta → Tangerang Selatan dan Bekasi. Di atas Rp 7 juta → Jakarta pusat/selatan. Temukan pilihan terlengkap di **SewaApartement.id**.`,
      en: `## JABODETABEK Apartment Price Comparison 2024\n\nJakarta: Studio from Rp 2.5M/month. BSD/Bintaro: Studio from Rp 2M/month. Bekasi: Studio from Rp 2M/month. Depok: Studio from Rp 1.5M/month (best for students). Find verified listings at SewaApartement.id.`,
    },
    category: { id: "Analisis Pasar", en: "Market Analysis" },
    tags: ["harga", "jabodetabek", "perbandingan", "2024"],
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
    author: "Tim Analis SewaApartement",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=60&q=80",
    publishedAt: "2024-02-20T08:00:00.000Z",
    readTime: 10,
    views: 3201,
    featured: false,
    autoGenerated: false,
  },
  {
    id: "seed-003",
    slug: "apartemen-terbaik-mahasiswa-depok-2024",
    topicId: "mahasiswa-depok",
    title: { id: "5 Apartemen Terbaik untuk Mahasiswa di Depok 2024", en: "5 Best Apartments for Students in Depok 2024" },
    excerpt: { id: "Rekomendasi apartemen terjangkau untuk mahasiswa UI, Gunadarma, dan kampus lainnya di Depok.", en: "Affordable apartment recommendations for students near major campuses in Depok." },
    content: {
      id: `## 5 Apartemen Terbaik untuk Mahasiswa di Depok 2024\n\nSebagai kota pelajar, Depok punya banyak pilihan apartemen dengan harga bersahabat.\n\n### 1. Margonda Residence 2, 3, 4, 5\nLokasinya paling strategis — terintegrasi dengan D'Mall Depok. Jarak 10 menit jalan kaki ke UI. Harga studio mulai **Rp 1,5 juta/bulan**.\n\n### 2. Atlanta Residences Depok\nDekat Universitas Indonesia dan Stasiun Depok Baru. Cocok untuk mahasiswa yang butuh akses KRL cepat ke Jakarta.\n\n### 3. De Papilio Tamansari\nApartemen modern dengan konsep green building. Harga terjangkau dan dekat kampus.\n\n### 4. Grand Depok City\nKawasan terintegrasi dengan mall. Cocok untuk mahasiswa yang ingin kenyamanan lengkap.\n\n### 5. Bogor Icon (untuk mahasiswa IPB)\nStrategis untuk mahasiswa IPB dengan pemandangan Gunung Salak.\n\n### Tips Memilih\n- Prioritaskan dekat transportasi publik (KRL/Angkot)\n- Pastikan WiFi sudah include\n- Cek apakah listrik dan air sudah include\n\nCari semua pilihan terbaik di **SewaApartement.id** — platform sewa apartemen JABODETABEK terlengkap.`,
      en: `## 5 Best Apartments for Students in Depok 2024\n\nMargonda Residence (from Rp 1.5M/month), Atlanta Residences, De Papilio, Grand Depok City, and Bogor Icon are top picks. Find them all at SewaApartement.id.`,
    },
    category: { id: "Rekomendasi", en: "Recommendation" },
    tags: ["mahasiswa", "depok", "UI", "murah"],
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    author: "Tim Redaksi SewaApartement",
    authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=60&q=80",
    publishedAt: "2024-02-10T08:00:00.000Z",
    readTime: 6,
    views: 2107,
    featured: false,
    autoGenerated: false,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Semua artikel = seed + cache (in-memory generated)
// ─────────────────────────────────────────────────────────────────────────────
function getAllArticles() {
  const cached = getCache();
  // Merge seed + cached, hindari duplikat by id
  const seedIds = new Set(SEED_BLOGS.map((s) => s.id));
  const cachedOnly = cached.filter((a) => !seedIds.has(a.id));
  return [...SEED_BLOGS, ...cachedOnly].sort(
    (a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Weekly topics — 8 topik berputar
// ─────────────────────────────────────────────────────────────────────────────
const WEEKLY_TOPICS = [
  {
    id: "tips-nego",
    title: { id: "Tips Jitu Negosiasi Harga Sewa Apartemen di JABODETABEK", en: "Smart Tips to Negotiate Apartment Rent in JABODETABEK" },
    category: { id: "Tips & Trik", en: "Tips & Tricks" },
    keywords: ["negosiasi harga", "sewa apartemen", "tips hemat", "JABODETABEK"],
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
  },
  {
    id: "expat-friendly",
    title: { id: "10 Apartemen Paling Ramah Ekspatriat di Jakarta", en: "10 Most Expat-Friendly Apartments in Jakarta" },
    category: { id: "Rekomendasi", en: "Recommendation" },
    keywords: ["ekspatriat", "expat", "jakarta", "apartemen premium", "SCBD"],
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
  },
  {
    id: "tren-pasar",
    title: { id: "Tren Pasar Sewa Apartemen JABODETABEK Terkini", en: "Latest JABODETABEK Apartment Rental Market Trends" },
    category: { id: "Analisis Pasar", en: "Market Analysis" },
    keywords: ["tren properti", "pasar sewa", "JABODETABEK", "analisis pasar"],
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
  },
  {
    id: "studio-vs-1br",
    title: { id: "Studio vs 1 Bedroom: Mana yang Lebih Menguntungkan?", en: "Studio vs 1 Bedroom: Which is the Better Deal?" },
    category: { id: "Panduan", en: "Guide" },
    keywords: ["studio", "1 bedroom", "perbandingan tipe apartemen", "tips memilih"],
    image: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80",
  },
  {
    id: "checklist-sewa",
    title: { id: "Checklist 20 Poin Wajib Sebelum Tanda Tangan Kontrak Sewa", en: "20-Point Checklist Before Signing Your Rental Contract" },
    category: { id: "Panduan", en: "Guide" },
    keywords: ["checklist sewa", "kontrak apartemen", "tips sewa", "sebelum sewa"],
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
  },
  {
    id: "bsd-vs-bintaro",
    title: { id: "BSD City vs Bintaro: Perbandingan Lengkap untuk Hunian 2024", en: "BSD City vs Bintaro: Complete Comparison for Living in 2024" },
    category: { id: "Perbandingan", en: "Comparison" },
    keywords: ["BSD City", "Bintaro", "Tangerang Selatan", "perbandingan kawasan hunian"],
    image: "https://images.unsplash.com/photo-1567327613485-fbc7bf196198?w=800&q=80",
  },
  {
    id: "investasi-properti",
    title: { id: "Apartemen Sewaan: Strategi Investasi Properti Passive Income", en: "Rental Apartments: Property Investment Strategy for Passive Income" },
    category: { id: "Investasi", en: "Investment" },
    keywords: ["investasi properti", "passive income apartemen", "ROI sewa", "JABODETABEK"],
    image: "https://images.unsplash.com/photo-1560185008-a33f5c7b1844?w=800&q=80",
  },
  {
    id: "panduan-bekasi",
    title: { id: "Panduan Lengkap Sewa Apartemen di Bekasi: Area, Harga & Tips", en: "Complete Guide to Renting Apartments in Bekasi: Areas, Prices & Tips" },
    category: { id: "Panduan", en: "Guide" },
    keywords: ["apartemen bekasi", "Summarecon Bekasi", "harga sewa bekasi", "kawasan bekasi"],
    image: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800&q=80",
  },
];

function slugify(text: string) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .trim();
}

// ─────────────────────────────────────────────────────────────────────────────
// Mistral AI — generate konten artikel
// ─────────────────────────────────────────────────────────────────────────────
async function generateWithMistral(topic: (typeof WEEKLY_TOPICS)[0]) {
  const apiKey = process.env.MISTRAL_API_KEY;
  if (!apiKey) return generateFallback(topic);

  const prompt = `Kamu adalah penulis konten properti profesional Indonesia untuk website SewaApartement.id — platform marketplace sewa apartemen JABODETABEK.

Tulis artikel blog yang informatif, menarik, dan SEO-friendly tentang:
"${topic.title.id}"

Keywords yang HARUS masuk secara natural: ${topic.keywords.join(", ")}

Aturan PENTING:
- Minimal 500 kata untuk content_id
- Gunakan format Markdown: ## untuk heading, **bold**, - untuk list
- Tulis dengan gaya profesional namun ramah
- Selipkan "SewaApartement.id" secara natural di 1-2 tempat
- Output HANYA JSON valid, tidak ada teks lain di luar JSON

Output format:
{
  "title_id": "judul menarik bahasa Indonesia",
  "title_en": "English title",
  "excerpt_id": "ringkasan 2 kalimat menarik bahasa Indonesia",
  "excerpt_en": "2-sentence English summary",
  "content_id": "konten lengkap markdown bahasa Indonesia 500+ kata",
  "content_en": "full English markdown content 400+ words",
  "tags": ["tag1", "tag2", "tag3", "tag4", "tag5"]
}`;

  try {
    const res = await fetch("https://api.mistral.ai/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "mistral-small-latest",
        messages: [{ role: "user", content: prompt }],
        temperature: 0.7,
        max_tokens: 4096,
        response_format: { type: "json_object" },
      }),
    });

    if (!res.ok) {
      const errBody = await res.text();
      throw new Error(`Mistral ${res.status}: ${errBody}`);
    }

    const data = await res.json();
    const raw = (data.choices?.[0]?.message?.content ?? "").trim();
    const cleaned = raw
      .replace(/^```json\s*/i, "")
      .replace(/^```\s*/i, "")
      .replace(/\s*```$/i, "")
      .trim();
    return JSON.parse(cleaned);
  } catch (err: any) {
    console.error("[Mistral] Error:", err.message);
    // Fallback jika Mistral error
    return generateFallback(topic);
  }
}

function generateFallback(topic: (typeof WEEKLY_TOPICS)[0]) {
  const month = new Date().toLocaleString("id-ID", { month: "long", year: "numeric" });
  return {
    title_id: topic.title.id,
    title_en: topic.title.en,
    excerpt_id: `Panduan lengkap tentang ${topic.keywords[0]} di JABODETABEK — ${month}. Tips dan rekomendasi terpercaya dari SewaApartement.id.`,
    excerpt_en: `Complete guide about ${topic.keywords[0]} in JABODETABEK. Trusted tips and recommendations from SewaApartement.id.`,
    content_id: `## ${topic.title.id}\n\nPasar properti JABODETABEK terus berkembang pesat pada ${month}. **${topic.keywords[0]}** menjadi salah satu topik yang paling banyak dicari.\n\n### Mengapa Ini Penting?\n\nDengan harga sewa yang terus bergerak, memiliki informasi yang tepat adalah kunci untuk mendapatkan hunian terbaik sesuai budget.\n\n### Tips Utama\n\n- **Riset terlebih dahulu** — bandingkan harga di beberapa platform\n- **Gunakan filter lengkap** — sesuaikan kota, tipe unit, dan harga\n- **Hubungi langsung pemilik** — negosiasi lebih fleksibel via WhatsApp\n- **Perhatikan fasilitas include** — WiFi, listrik, air, IPL, parkir\n- **Cek lokasi** — akses transportasi publik sangat mempengaruhi kenyamanan\n\n### Kesimpulan\n\nTemukan 2.940+ listing apartemen terverifikasi di seluruh JABODETABEK hanya di **[SewaApartement.id](https://sewa-apartement-claude.vercel.app)** — hubungi pemilik langsung via WhatsApp tanpa perantara.`,
    content_en: `## ${topic.title.en}\n\nThe JABODETABEK property market continues to grow. Find the best options at SewaApartement.id — 2,940+ verified listings, direct WhatsApp contact with owners.`,
    tags: topic.keywords,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// POST — dipanggil manual dari blog page (tombol Generate)
// ─────────────────────────────────────────────────────────────────────────────
export async function POST(req: NextRequest) {
  const authHeader = req.headers.get("authorization");
  const cronSecret = process.env.CRON_SECRET || "sewa-cron-secret-2024";
  const isVercelCron = req.headers.get("x-vercel-cron") === "1";

  if (!isVercelCron && authHeader !== `Bearer ${cronSecret}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const allArticles = getAllArticles();
    const weeksSinceEpoch = Math.floor(Date.now() / (7 * 24 * 60 * 60 * 1000));
    const topicIndex = weeksSinceEpoch % WEEKLY_TOPICS.length;
    const topic = WEEKLY_TOPICS[topicIndex];

    // Cek duplikat minggu ini
    const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
    const alreadyExists = allArticles.some(
      (b) => b.topicId === topic.id && new Date(b.publishedAt) > sevenDaysAgo
    );
    if (alreadyExists) {
      return NextResponse.json({
        success: false,
        message: `Artikel topik "${topic.title.id}" sudah ada minggu ini.`,
      });
    }

    // Generate dengan Mistral (atau fallback)
    const generated = await generateWithMistral(topic);

    const now = new Date();
    const slug = `${slugify(generated.title_id)}-${now.toISOString().split("T")[0]}`;

    const newArticle = {
      id: `auto-${Date.now()}`,
      slug,
      topicId: topic.id,
      title: { id: generated.title_id, en: generated.title_en },
      excerpt: { id: generated.excerpt_id, en: generated.excerpt_en },
      content: { id: generated.content_id, en: generated.content_en },
      category: topic.category,
      tags: generated.tags || topic.keywords,
      image: topic.image,
      author: "AI Redaksi SewaApartement",
      authorAvatar: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=60&q=80",
      publishedAt: now.toISOString(),
      readTime: Math.max(3, Math.ceil((generated.content_id?.length || 1500) / 1200)),
      views: 0,
      featured: false,
      autoGenerated: true,
      generatedWithAI: !!process.env.MISTRAL_API_KEY,
    };

    // Simpan ke in-memory cache
    addToCache(newArticle);

    return NextResponse.json({
      success: true,
      message: `✅ Artikel berhasil dibuat: "${newArticle.title.id}"`,
      article: {
        id: newArticle.id,
        slug: newArticle.slug,
        title: newArticle.title,
        publishedAt: newArticle.publishedAt,
        generatedWithAI: newArticle.generatedWithAI,
      },
      // Kirim artikel lengkap agar frontend bisa simpan ke localStorage
      fullArticle: newArticle,
    });
  } catch (err: any) {
    console.error("[generate-blog POST] Error:", err);
    return NextResponse.json(
      { success: false, error: err.message || "Internal server error" },
      { status: 500 }
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// GET — dipanggil Vercel Cron (Cron hanya support GET/HEAD)
// Juga untuk preview status topik minggu ini
// ─────────────────────────────────────────────────────────────────────────────
export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const isStatusCheck = searchParams.get("status") === "1";

  // Status check publik (tanpa auth) — untuk debugging
  if (isStatusCheck) {
    const weeksSinceEpoch = Math.floor(Date.now() / (7 * 24 * 60 * 60 * 1000));
    return NextResponse.json({
      ok: true,
      hasMistralKey: !!process.env.MISTRAL_API_KEY,
      currentTopic: WEEKLY_TOPICS[weeksSinceEpoch % WEEKLY_TOPICS.length].title.id,
      totalCached: getCache().length,
      totalArticles: getAllArticles().length,
    });
  }

  // Cron execution (dipanggil Vercel Cron tiap Senin)
  const isVercelCron = req.headers.get("x-vercel-cron") === "1";
  const authHeader = req.headers.get("authorization");
  const cronSecret = process.env.CRON_SECRET || "sewa-cron-secret-2024";

  if (!isVercelCron && authHeader !== `Bearer ${cronSecret}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Jalankan generate via GET (untuk Vercel Cron)
  try {
    const allArticles = getAllArticles();
    const weeksSinceEpoch = Math.floor(Date.now() / (7 * 24 * 60 * 60 * 1000));
    const topicIndex = weeksSinceEpoch % WEEKLY_TOPICS.length;
    const topic = WEEKLY_TOPICS[topicIndex];

    const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
    const alreadyExists = allArticles.some(
      (b) => b.topicId === topic.id && new Date(b.publishedAt) > sevenDaysAgo
    );
    if (alreadyExists) {
      return NextResponse.json({ success: false, message: "Sudah ada artikel minggu ini." });
    }

    const generated = await generateWithMistral(topic);
    const now = new Date();
    const newArticle = {
      id: `auto-${Date.now()}`,
      slug: `${slugify(generated.title_id)}-${now.toISOString().split("T")[0]}`,
      topicId: topic.id,
      title: { id: generated.title_id, en: generated.title_en },
      excerpt: { id: generated.excerpt_id, en: generated.excerpt_en },
      content: { id: generated.content_id, en: generated.content_en },
      category: topic.category,
      tags: generated.tags || topic.keywords,
      image: topic.image,
      author: "AI Redaksi SewaApartement",
      authorAvatar: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=60&q=80",
      publishedAt: now.toISOString(),
      readTime: Math.max(3, Math.ceil((generated.content_id?.length || 1500) / 1200)),
      views: 0,
      featured: false,
      autoGenerated: true,
      generatedWithAI: !!process.env.MISTRAL_API_KEY,
    };

    addToCache(newArticle);
    return NextResponse.json({ success: true, message: `Generated: "${newArticle.title.id}"`, slug: newArticle.slug });
  } catch (err: any) {
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}
