"use client";

import { useEffect, useState, useRef } from "react";
import React from "react";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import {
  ArrowLeft, Calendar, Clock, Tag, Share2,
  ArrowRight, Sparkles, Eye, Copy, Check,
} from "lucide-react";
import { useLanguage } from "@/hooks/useLanguage";
import { BLOG_POSTS } from "@/lib/data";

interface BlogPost {
  id: string;
  slug: string;
  title: { id: string; en: string };
  excerpt: { id: string; en: string };
  content?: { id: string; en: string };
  category: { id: string; en: string };
  image: string;
  author: string;
  authorAvatar?: string;
  publishedAt?: string;
  date?: string;
  readTime: number;
  views?: number;
  featured?: boolean;
  autoGenerated?: boolean;
  tags?: string[];
}

// Sanitize HTML — strip script/iframe/event handlers sebelum inject ke DOM
function sanitizeHtml(html: string): string {
  return html
    .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, "")
    .replace(/<iframe\b[^<]*(?:(?!<\/iframe>)<[^<]*)*<\/iframe>/gi, "")
    .replace(/\son\w+\s*=\s*["'][^"']*["']/gi, "")
    .replace(/javascript:/gi, "")
    .replace(/data:text\/html/gi, "");
}

// Very simple markdown → HTML (bold, headings, lists, paragraphs)
function renderMarkdown(md: string): string {
  if (!md) return "";
  return md
    .replace(/^### (.+)$/gm, '<h3 class="text-lg font-bold text-white mt-8 mb-3">$1</h3>')
    .replace(/^## (.+)$/gm,  '<h2 class="text-xl font-bold text-white mt-10 mb-4">$1</h2>')
    .replace(/^# (.+)$/gm,   '<h1 class="text-2xl font-black text-white mt-12 mb-4">$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong class="text-white font-semibold">$1</strong>')
    .replace(/\*(.+?)\*/g,    '<em class="italic">$1</em>')
    .replace(/^\- (.+)$/gm,   '<li class="ml-4 list-disc text-white/70 mb-1">$1</li>')
    .replace(/^\d+\. (.+)$/gm,'<li class="ml-4 list-decimal text-white/70 mb-1">$1</li>')
    .replace(/(<li.*<\/li>\n?)+/g, '<ul class="space-y-1 my-4">$&</ul>')
    .replace(/\n\n/g, '</p><p class="text-white/70 leading-relaxed mb-4">')
    .replace(/^(?!<[h|u|l])(.+)/, '<p class="text-white/70 leading-relaxed mb-4">$1')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g,
      '<a href="$2" class="text-primary-400 hover:text-primary-300 underline underline-offset-2" target="_blank">$1</a>');
}

export default function BlogDetailPage({ params }: { params: { slug: string } }) {
  const { lang, t } = useLanguage();
  const [post, setPost]           = useState<BlogPost | null>(null);
  const [related, setRelated]     = useState<BlogPost[]>([]);
  const [loading, setLoading]     = useState(true);
  const [copied, setCopied]       = useState(false);
  const copyTimerRef              = React.useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    async function load() {
      setLoading(true);
      // 1. Try API first
      try {
        const res = await fetch(`/api/blogs?slug=${params.slug}`);
        if (res.ok) {
          const data = await res.json();
          if (data && data.id) {
            setPost(data);
            const allRes = await fetch("/api/blogs");
            if (allRes.ok) {
              const all: BlogPost[] = await allRes.json();
              setRelated(all.filter(p => p.slug !== params.slug).slice(0, 2));
            }
            setLoading(false);
            return;
          }
        }
      } catch {/* fallback */}

      // 2. Try localStorage (AI-generated articles saved client-side)
      try {
        const local: BlogPost[] = JSON.parse(localStorage.getItem("sewa-ai-articles") ?? "[]");
        const found = local.find(p => p.slug === params.slug);
        if (found) {
          setPost(found);
          setRelated(local.filter(p => p.slug !== params.slug).slice(0, 2));
          setLoading(false);
          return;
        }
      } catch {/* ignore */}

      // 3. Fallback: static seed
      const found = (BLOG_POSTS as any[]).find(p => p.slug === params.slug);
      if (found) {
        setPost(found);
        setRelated((BLOG_POSTS as any[]).filter(p => p.slug !== params.slug).slice(0, 2));
      }
      setLoading(false);
    }
    load();
  }, [params.slug]);

  const handleCopy = () => {
    navigator.clipboard.writeText(window.location.href);
    setCopied(true);
    if (copyTimerRef.current) clearTimeout(copyTimerRef.current);
    copyTimerRef.current = setTimeout(() => setCopied(false), 2000);
  };

  // Cleanup timer on unmount
  useEffect(() => {
    return () => { if (copyTimerRef.current) clearTimeout(copyTimerRef.current); };
  }, []);

  const handleWhatsAppShare = () => {
    const text = `Baca artikel menarik ini: ${t(post?.title ?? { id: "", en: "" })} — ${window.location.href}`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, "_blank");
  };

  const handleTelegramShare = () => {
    const text = `Baca artikel menarik ini: ${t(post?.title ?? { id: "", en: "" })}`;
    window.open(`https://t.me/share/url?url=${encodeURIComponent(window.location.href)}&text=${encodeURIComponent(text)}`, "_blank");
  };

  const handleLineShare = () => {
    window.open(`https://social-plugins.line.me/lineit/share?url=${encodeURIComponent(window.location.href)}`, "_blank");
  };

  if (loading) {
    return (
      <div className="page-dark pt-20 min-h-screen">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-6">
          <div className="skeleton h-64 md:h-96 rounded-3xl w-full" />
          <div className="skeleton h-8 w-3/4 rounded" />
          <div className="skeleton h-5 w-1/2 rounded" />
          <div className="space-y-3">
            {[...Array(6)].map((_, i) => (
              <div key={i} className="skeleton h-4 rounded" style={{ width: `${85 + Math.random() * 15}%` }} />
            ))}
          </div>
        </div>
      </div>
    );
  }

  if (!post) {
    return (
      <div className="page-dark pt-20 min-h-screen flex items-center justify-center px-4">
        <div className="text-center">
          <div className="text-5xl mb-4">📄</div>
          <h1 className="text-white font-bold text-2xl mb-3">
            {lang === "id" ? "Artikel tidak ditemukan" : "Article not found"}
          </h1>
          <Link href="/blog" className="btn-primary inline-flex items-center gap-2 mt-4">
            <ArrowLeft size={16} />
            {lang === "id" ? "Kembali ke Blog" : "Back to Blog"}
          </Link>
        </div>
      </div>
    );
  }

  const publishDate = post.publishedAt ?? post.date ?? "";
  const contentHtml = post.content ? sanitizeHtml(renderMarkdown(t(post.content))) : null;

  // Static content fallback (seed posts that have no .content field)
  const staticContent = (post as any).content
    ? null
    : lang === "id"
      ? `<p class="text-white/70 leading-relaxed mb-4">${t(post.excerpt)}</p>
         <p class="text-white/70 leading-relaxed mb-4">Konten lengkap artikel ini sedang disiapkan. Kunjungi kembali sebentar lagi, atau jelajahi artikel lainnya di bawah.</p>`
      : `<p class="text-white/70 leading-relaxed mb-4">${t(post.excerpt)}</p>
         <p class="text-white/70 leading-relaxed mb-4">Full article content is being prepared. Check back soon, or explore other articles below.</p>`;

  return (
    <div className="page-dark pt-16 md:pt-20">
      {/* Hero Image */}
      <div className="relative h-56 md:h-96 overflow-hidden">
        <Image src={post.image} alt={t(post.title)} fill
          className="object-cover" priority sizes="100vw" />
        <div className="absolute inset-0 bg-gradient-to-t from-dark-900 via-dark-900/50 to-transparent" />
        {post.autoGenerated && (
          <div className="absolute top-4 right-4 flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-accent-500/80 backdrop-blur-md text-white text-xs font-semibold border border-accent-400/50">
            <Sparkles size={12} /> AI Generated
          </div>
        )}
      </div>

      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Back */}
        <Link href="/blog" className="inline-flex items-center gap-2 text-white/50 hover:text-white text-sm mb-6 group">
          <ArrowLeft size={15} className="group-hover:-translate-x-1 transition-transform" />
          {lang === "id" ? "Kembali ke Blog" : "Back to Blog"}
        </Link>

        {/* Meta */}
        <div className="flex flex-wrap items-center gap-3 mb-4">
          <span className="badge bg-primary-600/20 text-primary-400 border border-primary-500/30 text-xs">
            <Tag size={10} /> {t(post.category)}
          </span>
          {publishDate && (
            <div className="flex items-center gap-1 text-white/40 text-xs">
              <Calendar size={11} />
              {new Date(publishDate).toLocaleDateString(
                lang === "id" ? "id-ID" : "en-US",
                { year: "numeric", month: "long", day: "numeric" }
              )}
            </div>
          )}
          <div className="flex items-center gap-1 text-white/40 text-xs">
            <Clock size={11} /> {post.readTime} min {lang === "id" ? "baca" : "read"}
          </div>
          {(post.views ?? 0) > 0 && (
            <div className="flex items-center gap-1 text-white/40 text-xs">
              <Eye size={11} /> {post.views} views
            </div>
          )}
        </div>

        {/* Title */}
        <motion.h1 initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
          className="font-heading font-black text-white text-2xl md:text-3xl leading-tight mb-5">
          {t(post.title)}
        </motion.h1>

        {/* Author */}
        <div className="flex items-center gap-3 mb-2">
          {post.authorAvatar && (
            <div className="relative w-9 h-9 rounded-full overflow-hidden flex-shrink-0">
              <Image src={post.authorAvatar} alt={post.author} fill className="object-cover" sizes="36px" />
            </div>
          )}
          <div>
            <p className="text-white/80 text-sm font-medium">{post.author}</p>
            {post.autoGenerated && (
              <p className="text-accent-400/70 text-xs flex items-center gap-1">
                <Sparkles size={9} /> {lang === "id" ? "Dibuat dengan AI" : "Created with AI"}
              </p>
            )}
          </div>
        </div>

        <div className="section-divider my-6" />

        {/* Article content */}
        <motion.article initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.15 }}
          className="prose-custom"
          dangerouslySetInnerHTML={{ __html: contentHtml ?? staticContent ?? "" }}
        />

        {/* Tags */}
        {post.tags && post.tags.length > 0 && (
          <div className="flex flex-wrap gap-2 mt-8">
            {post.tags.map(tag => (
              <span key={tag} className="tag-pill text-xs"># {tag}</span>
            ))}
          </div>
        )}

        <div className="section-divider my-8" />

        {/* Share */}
        <div className="flex items-center justify-between flex-wrap gap-3">
          <p className="text-white/40 text-sm">{lang === "id" ? "Bagikan artikel ini:" : "Share this article:"}</p>
          <div className="flex flex-wrap gap-2">

            {/* WhatsApp — logo resmi hijau */}
            <button onClick={handleWhatsAppShare}
              className="flex items-center gap-2 px-3 py-2 rounded-xl bg-white/5 border border-white/10 hover:bg-[#25D366]/15 hover:border-[#25D366]/40 text-white/60 hover:text-[#25D366] text-xs font-medium transition-all">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" aria-label="WhatsApp">
                <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347z"/><path d="M12 0C5.373 0 0 5.373 0 12c0 2.127.556 4.124 1.528 5.857L0 24l6.335-1.652A11.954 11.954 0 0012 24c6.627 0 12-5.373 12-12S18.627 0 12 0zm0 22c-1.885 0-3.65-.52-5.157-1.424l-.37-.22-3.763.984.999-3.662-.24-.376A9.961 9.961 0 012 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10z"/>
              </svg>
              WhatsApp
            </button>

            {/* Telegram — logo resmi biru langit */}
            <button onClick={handleTelegramShare}
              className="flex items-center gap-2 px-3 py-2 rounded-xl bg-white/5 border border-white/10 hover:bg-[#229ED9]/15 hover:border-[#229ED9]/40 text-white/60 hover:text-[#229ED9] text-xs font-medium transition-all">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" aria-label="Telegram">
                <path d="M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0zm5.562 8.248-2.03 9.571c-.145.658-.537.818-1.084.508l-3-2.21-1.447 1.394c-.16.16-.295.295-.605.295l.213-3.053 5.56-5.023c.242-.213-.054-.333-.373-.12L6.515 14.27l-2.948-.924c-.64-.203-.653-.64.136-.948l11.498-4.432c.534-.194 1.001.13.361.282z"/>
              </svg>
              Telegram
            </button>

            {/* LINE — logo resmi hijau LINE */}
            <button onClick={handleLineShare}
              className="flex items-center gap-2 px-3 py-2 rounded-xl bg-white/5 border border-white/10 hover:bg-[#06C755]/15 hover:border-[#06C755]/40 text-white/60 hover:text-[#06C755] text-xs font-medium transition-all">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" aria-label="LINE">
                <path d="M12 .5C5.648.5.5 4.735.5 9.943c0 4.91 4.354 9.02 10.245 9.794.399.086.941.265 1.079.607.123.31.08.797.04 1.11l-.174 1.052c-.052.313-.242 1.222 1.072.666 1.313-.556 7.092-4.178 9.676-7.155C23.523 13.72 24.5 11.915 24.5 9.944 24.5 4.735 18.352.5 12 .5zM8.4 12.6H6.6a.6.6 0 0 1 0-1.2V8.4a.6.6 0 0 1 1.2 0v3.6h.6a.6.6 0 0 1 0 1.2l-1.2-.4zm2.4 0a.6.6 0 0 1-.6-.6V8.4a.6.6 0 0 1 1.2 0v3.6a.6.6 0 0 1-.6.6zm4.8 0H13.8a.6.6 0 0 1-.6-.6V8.4a.6.6 0 0 1 1.2 0v3h1.2a.6.6 0 0 1 0 1.2zm2.4 0h-1.2a.6.6 0 0 1 0-1.2h.6V9.6h-.6a.6.6 0 0 1 0-1.2h1.2a.6.6 0 0 1 .6.6v3a.6.6 0 0 1-.6.6z"/>
              </svg>
              LINE
            </button>

            {/* Copy Link */}
            <button onClick={handleCopy}
              className="flex items-center gap-2 px-3 py-2 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 text-white/60 hover:text-white text-xs font-medium transition-all">
              {copied
                ? <><Check size={13} className="text-green-400" /><span className="text-green-400">{lang === "id" ? "Tersalin!" : "Copied!"}</span></>
                : <><Copy size={13} />{lang === "id" ? "Salin Link" : "Copy Link"}</>
              }
            </button>

          </div>
        </div>

        {/* Related */}
        {related.length > 0 && (
          <div className="mt-14">
            <h2 className="font-heading font-bold text-white text-xl mb-5">
              {lang === "id" ? "Artikel Terkait" : "Related Articles"}
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {related.map((r, i) => (
                <motion.div key={r.id} initial={{ opacity: 0, y: 12 }}
                  whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
                  transition={{ delay: i * 0.1 }}>
                  <Link href={`/blog/${r.slug}`} className="group flex gap-4 glass rounded-xl p-4 hover:border-primary-500/20 transition-all">
                    <div className="relative w-20 h-16 rounded-lg overflow-hidden flex-shrink-0">
                      <Image src={r.image} alt={t(r.title)} fill
                        className="object-cover group-hover:scale-110 transition-transform duration-300"
                        sizes="80px" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <h3 className="text-white text-sm font-medium leading-snug line-clamp-2 group-hover:text-primary-300 transition-colors">
                        {t(r.title)}
                      </h3>
                      <div className="flex items-center gap-2 text-white/30 text-xs mt-1.5">
                        <Clock size={10} /> {r.readTime} min
                        {r.autoGenerated && (
                          <span className="flex items-center gap-0.5 text-accent-400/70">
                            <Sparkles size={9} /> AI
                          </span>
                        )}
                      </div>
                    </div>
                    <ArrowRight size={14} className="text-white/20 flex-shrink-0 self-center group-hover:text-primary-400 transition-colors" />
                  </Link>
                </motion.div>
              ))}
            </div>
          </div>
        )}

        {/* CTA */}
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mt-12 p-6 glass rounded-2xl border border-primary-500/20 text-center">
          <h3 className="font-bold text-white text-lg mb-2">
            {lang === "id" ? "Siap Cari Apartemen?" : "Ready to Find Your Apartment?"}
          </h3>
          <p className="text-white/50 text-sm mb-4">
            {lang === "id"
              ? "2.940+ listing apartemen terverifikasi di seluruh JABODETABEK siap untuk Anda jelajahi."
              : "2,940+ verified apartment listings across JABODETABEK ready for you to explore."}
          </p>
          <Link href="/listings" className="btn-primary inline-flex items-center gap-2">
            {lang === "id" ? "Lihat Semua Listing" : "Browse All Listings"}
            <ArrowRight size={15} />
          </Link>
        </motion.div>
      </div>
    </div>
  );
}
