"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import {
  ArrowLeft, Calendar, Clock, Tag, Share2, Heart,
  ArrowRight, Sparkles, Eye, Copy, Check,
} from "lucide-react";
import { useLanguage } from "@/hooks/useLanguage";
import { BLOG_POSTS } from "@/lib/data";

interface BlogPost {
  id: string;
  slug: string;
  title: { id: string; en: string };
  excerpt: { id: string; en: string };
  content?: { id: string; en: string };
  category: { id: string; en: string };
  image: string;
  author: string;
  authorAvatar?: string;
  publishedAt?: string;
  date?: string;
  readTime: number;
  views?: number;
  featured?: boolean;
  autoGenerated?: boolean;
  tags?: string[];
}

// Sanitize HTML — strip script/iframe/event handlers sebelum inject ke DOM
function sanitizeHtml(html: string): string {
  return html
    .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, "")
    .replace(/<iframe\b[^<]*(?:(?!<\/iframe>)<[^<]*)*<\/iframe>/gi, "")
    .replace(/\son\w+\s*=\s*["'][^"']*["']/gi, "")
    .replace(/javascript:/gi, "")
    .replace(/data:text\/html/gi, "");
}

// Very simple markdown → HTML (bold, headings, lists, paragraphs)
function renderMarkdown(md: string): string {
  if (!md) return "";
  return md
    .replace(/^### (.+)$/gm, '<h3 class="text-lg font-bold text-white mt-8 mb-3">$1</h3>')
    .replace(/^## (.+)$/gm,  '<h2 class="text-xl font-bold text-white mt-10 mb-4">$1</h2>')
    .replace(/^# (.+)$/gm,   '<h1 class="text-2xl font-black text-white mt-12 mb-4">$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong class="text-white font-semibold">$1</strong>')
    .replace(/\*(.+?)\*/g,    '<em class="italic">$1</em>')
    .replace(/^\- (.+)$/gm,   '<li class="ml-4 list-disc text-white/70 mb-1">$1</li>')
    .replace(/^\d+\. (.+)$/gm,'<li class="ml-4 list-decimal text-white/70 mb-1">$1</li>')
    .replace(/(<li.*<\/li>\n?)+/g, '<ul class="space-y-1 my-4">$&</ul>')
    .replace(/\n\n/g, '</p><p class="text-white/70 leading-relaxed mb-4">')
    .replace(/^(?!<[h|u|l])(.+)/, '<p class="text-white/70 leading-relaxed mb-4">$1')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g,
      '<a href="$2" class="text-primary-400 hover:text-primary-300 underline underline-offset-2" target="_blank">$1</a>');
}

export default function BlogDetailPage({ params }: { params: { slug: string } }) {
  const { lang, t } = useLanguage();
  const [post, setPost]           = useState<BlogPost | null>(null);
  const [related, setRelated]     = useState<BlogPost[]>([]);
  const [loading, setLoading]     = useState(true);
  const [liked, setLiked]         = useState(false);
  const [copied, setCopied]       = useState(false);

  useEffect(() => {
    async function load() {
      setLoading(true);
      // 1. Try API first
      try {
        const res = await fetch(`/api/blogs?slug=${params.slug}`);
        if (res.ok) {
          const data = await res.json();
          if (data && data.id) {
            setPost(data);
            const allRes = await fetch("/api/blogs");
            if (allRes.ok) {
              const all: BlogPost[] = await allRes.json();
              setRelated(all.filter(p => p.slug !== params.slug).slice(0, 2));
            }
            setLoading(false);
            return;
          }
        }
      } catch {/* fallback */}

      // 2. Try localStorage (AI-generated articles saved client-side)
      try {
        const local: BlogPost[] = JSON.parse(localStorage.getItem("sewa-ai-articles") ?? "[]");
        const found = local.find(p => p.slug === params.slug);
        if (found) {
          setPost(found);
          setRelated(local.filter(p => p.slug !== params.slug).slice(0, 2));
          setLoading(false);
          return;
        }
      } catch {/* ignore */}

      // 3. Fallback: static seed
      const found = (BLOG_POSTS as any[]).find(p => p.slug === params.slug);
      if (found) {
        setPost(found);
        setRelated((BLOG_POSTS as any[]).filter(p => p.slug !== params.slug).slice(0, 2));
      }
      setLoading(false);
    }
    load();
  }, [params.slug]);

  const handleCopy = () => {
    navigator.clipboard.writeText(window.location.href);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleWhatsAppShare = () => {
    const text = `Baca artikel menarik ini: ${t(post?.title ?? { id: "", en: "" })} — ${window.location.href}`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, "_blank");
  };

  if (loading) {
    return (
      <div className="page-dark pt-20 min-h-screen">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-6">
          <div className="skeleton h-64 md:h-96 rounded-3xl w-full" />
          <div className="skeleton h-8 w-3/4 rounded" />
          <div className="skeleton h-5 w-1/2 rounded" />
          <div className="space-y-3">
            {[...Array(6)].map((_, i) => (
              <div key={i} className="skeleton h-4 rounded" style={{ width: `${85 + Math.random() * 15}%` }} />
            ))}
          </div>
        </div>
      </div>
    );
  }

  if (!post) {
    return (
      <div className="page-dark pt-20 min-h-screen flex items-center justify-center px-4">
        <div className="text-center">
          <div className="text-5xl mb-4">📄</div>
          <h1 className="text-white font-bold text-2xl mb-3">
            {lang === "id" ? "Artikel tidak ditemukan" : "Article not found"}
          </h1>
          <Link href="/blog" className="btn-primary inline-flex items-center gap-2 mt-4">
            <ArrowLeft size={16} />
            {lang === "id" ? "Kembali ke Blog" : "Back to Blog"}
          </Link>
        </div>
      </div>
    );
  }

  const publishDate = post.publishedAt ?? post.date ?? "";
  const contentHtml = post.content ? sanitizeHtml(renderMarkdown(t(post.content))) : null;

  // Static content fallback (seed posts that have no .content field)
  const staticContent = (post as any).content
    ? null
    : lang === "id"
      ? `<p class="text-white/70 leading-relaxed mb-4">${t(post.excerpt)}</p>
         <p class="text-white/70 leading-relaxed mb-4">Konten lengkap artikel ini sedang disiapkan. Kunjungi kembali sebentar lagi, atau jelajahi artikel lainnya di bawah.</p>`
      : `<p class="text-white/70 leading-relaxed mb-4">${t(post.excerpt)}</p>
         <p class="text-white/70 leading-relaxed mb-4">Full article content is being prepared. Check back soon, or explore other articles below.</p>`;

  return (
    <div className="page-dark pt-16 md:pt-20">
      {/* Hero Image */}
      <div className="relative h-56 md:h-96 overflow-hidden">
        <Image src={post.image} alt={t(post.title)} fill
          className="object-cover" priority sizes="100vw" />
        <div className="absolute inset-0 bg-gradient-to-t from-dark-900 via-dark-900/50 to-transparent" />
        {post.autoGenerated && (
          <div className="absolute top-4 right-4 flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-accent-500/80 backdrop-blur-md text-white text-xs font-semibold border border-accent-400/50">
            <Sparkles size={12} /> AI Generated
          </div>
        )}
      </div>

      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Back */}
        <Link href="/blog" className="inline-flex items-center gap-2 text-white/50 hover:text-white text-sm mb-6 group">
          <ArrowLeft size={15} className="group-hover:-translate-x-1 transition-transform" />
          {lang === "id" ? "Kembali ke Blog" : "Back to Blog"}
        </Link>

        {/* Meta */}
        <div className="flex flex-wrap items-center gap-3 mb-4">
          <span className="badge bg-primary-600/20 text-primary-400 border border-primary-500/30 text-xs">
            <Tag size={10} /> {t(post.category)}
          </span>
          {publishDate && (
            <div className="flex items-center gap-1 text-white/40 text-xs">
              <Calendar size={11} />
              {new Date(publishDate).toLocaleDateString(
                lang === "id" ? "id-ID" : "en-US",
                { year: "numeric", month: "long", day: "numeric" }
              )}
            </div>
          )}
          <div className="flex items-center gap-1 text-white/40 text-xs">
            <Clock size={11} /> {post.readTime} min {lang === "id" ? "baca" : "read"}
          </div>
          {(post.views ?? 0) > 0 && (
            <div className="flex items-center gap-1 text-white/40 text-xs">
              <Eye size={11} /> {post.views} views
            </div>
          )}
        </div>

        {/* Title */}
        <motion.h1 initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
          className="font-heading font-black text-white text-2xl md:text-3xl leading-tight mb-5">
          {t(post.title)}
        </motion.h1>

        {/* Author */}
        <div className="flex items-center gap-3 mb-2">
          {post.authorAvatar && (
            <div className="relative w-9 h-9 rounded-full overflow-hidden flex-shrink-0">
              <Image src={post.authorAvatar} alt={post.author} fill className="object-cover" sizes="36px" />
            </div>
          )}
          <div>
            <p className="text-white/80 text-sm font-medium">{post.author}</p>
            {post.autoGenerated && (
              <p className="text-accent-400/70 text-xs flex items-center gap-1">
                <Sparkles size={9} /> {lang === "id" ? "Dibuat dengan AI" : "Created with AI"}
              </p>
            )}
          </div>
        </div>

        <div className="section-divider my-6" />

        {/* Article content */}
        <motion.article initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.15 }}
          className="prose-custom"
          dangerouslySetInnerHTML={{ __html: contentHtml ?? staticContent ?? "" }}
        />

        {/* Tags */}
        {post.tags && post.tags.length > 0 && (
          <div className="flex flex-wrap gap-2 mt-8">
            {post.tags.map(tag => (
              <span key={tag} className="tag-pill text-xs"># {tag}</span>
            ))}
          </div>
        )}

        <div className="section-divider my-8" />

        {/* Share */}
        <div className="flex items-center justify-between flex-wrap gap-3">
          <p className="text-white/40 text-sm">{lang === "id" ? "Bagikan artikel ini:" : "Share this article:"}</p>
          <div className="flex gap-2">
            <button onClick={handleWhatsAppShare}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-white/5 border border-white/10 hover:bg-green-600/20 hover:border-green-500/30 text-white/60 hover:text-white text-xs transition-all">
              💬 WhatsApp
            </button>
            <button onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 text-white/60 hover:text-white text-xs transition-all">
              {copied ? <><Check size={12} className="text-green-400" /> Tersalin!</> : <><Copy size={12} /> Copy Link</>}
            </button>
            <button onClick={() => setLiked(!liked)}
              className={`flex items-center gap-1.5 px-3 py-2 rounded-xl border text-xs transition-all ${liked ? "bg-red-500/20 border-red-500/40 text-red-400" : "bg-white/5 border-white/10 text-white/60 hover:text-white"}`}>
              <Heart size={12} className={liked ? "fill-red-400" : ""} />
              {lang === "id" ? "Suka" : "Like"}
            </button>
          </div>
        </div>

        {/* Related */}
        {related.length > 0 && (
          <div className="mt-14">
            <h2 className="font-heading font-bold text-white text-xl mb-5">
              {lang === "id" ? "Artikel Terkait" : "Related Articles"}
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {related.map((r, i) => (
                <motion.div key={r.id} initial={{ opacity: 0, y: 12 }}
                  whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
                  transition={{ delay: i * 0.1 }}>
                  <Link href={`/blog/${r.slug}`} className="group flex gap-4 glass rounded-xl p-4 hover:border-primary-500/20 transition-all">
                    <div className="relative w-20 h-16 rounded-lg overflow-hidden flex-shrink-0">
                      <Image src={r.image} alt={t(r.title)} fill
                        className="object-cover group-hover:scale-110 transition-transform duration-300"
                        sizes="80px" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <h3 className="text-white text-sm font-medium leading-snug line-clamp-2 group-hover:text-primary-300 transition-colors">
                        {t(r.title)}
                      </h3>
                      <div className="flex items-center gap-2 text-white/30 text-xs mt-1.5">
                        <Clock size={10} /> {r.readTime} min
                        {r.autoGenerated && (
                          <span className="flex items-center gap-0.5 text-accent-400/70">
                            <Sparkles size={9} /> AI
                          </span>
                        )}
                      </div>
                    </div>
                    <ArrowRight size={14} className="text-white/20 flex-shrink-0 self-center group-hover:text-primary-400 transition-colors" />
                  </Link>
                </motion.div>
              ))}
            </div>
          </div>
        )}

        {/* CTA */}
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mt-12 p-6 glass rounded-2xl border border-primary-500/20 text-center">
          <h3 className="font-bold text-white text-lg mb-2">
            {lang === "id" ? "Siap Cari Apartemen?" : "Ready to Find Your Apartment?"}
          </h3>
          <p className="text-white/50 text-sm mb-4">
            {lang === "id"
              ? "2.940+ listing apartemen terverifikasi di seluruh JABODETABEK siap untuk Anda jelajahi."
              : "2,940+ verified apartment listings across JABODETABEK ready for you to explore."}
          </p>
          <Link href="/listings" className="btn-primary inline-flex items-center gap-2">
            {lang === "id" ? "Lihat Semua Listing" : "Browse All Listings"}
            <ArrowRight size={15} />
          </Link>
        </motion.div>
      </div>
    </div>
  );
}
