import { NextRequest, NextResponse } from "next/server";

// ─── Seed articles — always available ────────────────────────────────────────
export const SEED_BLOGS = [
  {
    id: "seed-001",
    slug: "tips-sewa-apartemen-jakarta-pertama-kali",
    topicId: "tips-pertama",
    title: { id: "10 Tips Sewa Apartemen di Jakarta untuk Pertama Kali", en: "10 Tips for Renting an Apartment in Jakarta for the First Time" },
    excerpt: { id: "Menyewa apartemen pertama kali di Jakarta bisa terasa membingungkan. Berikut panduan lengkap agar tidak salah pilih.", en: "Renting an apartment for the first time in Jakarta can feel confusing. Here is a complete guide." },
    content: {
      id: `## 10 Tips Sewa Apartemen di Jakarta untuk Pertama Kali\n\nMencari apartemen pertama di Jakarta memang butuh strategi. Berikut 10 tips yang perlu Anda ketahui:\n\n### 1. Tentukan Budget Sejak Awal\nAlokasikan maksimal 30% dari penghasilan bulanan untuk sewa. Jangan lupa perhitungkan biaya IPL, listrik, air, dan internet.\n\n### 2. Pilih Lokasi Strategis\nPertimbangkan jarak ke kantor/kampus, akses MRT/KRL/TransJakarta, dan fasilitas sekitar.\n\n### 3. Pahami Apa yang Include\nTanyakan apakah harga sudah include WiFi, listrik, air, IPL, dan parkir.\n\n### 4. Cek Kondisi Unit Langsung\nMinta video call atau kunjungi langsung sebelum deal. Perhatikan kondisi AC, plumbing, dan keamanan.\n\n### 5. Baca Kontrak dengan Teliti\nPerhatikan klausul deposit (biasanya 1-2 bulan), durasi kontrak minimum.\n\n### 6. Negosiasi Harga\nHarga listing bukan harga mati. Untuk kontrak tahunan, biasanya bisa nego 5-15%.\n\n### 7. Cek Keamanan Gedung\nPastikan ada CCTV, security 24 jam, dan sistem akses kartu.\n\n### 8. Perhatikan Arah Hadap Unit\nUnit hadap timur dapat sinar pagi yang baik.\n\n### 9. Tanya Tetangga atau Review Online\nCari review apartemen di Google Maps atau forum.\n\n### 10. Gunakan Platform Terpercaya\nCari listing di **SewaApartement.id** yang sudah terverifikasi dan langsung bisa kontak pemilik via WhatsApp tanpa perantara.`,
      en: `## 10 Tips for Renting an Apartment in Jakarta\n\nFinding your first apartment in Jakarta requires strategy. Set your budget, choose a strategic location, understand what's included, and use a trusted platform like SewaApartement.id to find verified listings.`,
    },
    category: { id: "Panduan", en: "Guide" },
    tags: ["tips", "jakarta", "pertama kali", "panduan sewa"],
    image: "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&q=80",
    author: "Tim Redaksi SewaApartement",
    authorAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=60&q=80",
    publishedAt: "2024-03-01T08:00:00.000Z",
    readTime: 7,
    views: 1842,
    featured: true,
    autoGenerated: false,
  },
  {
    id: "seed-002",
    slug: "perbandingan-harga-apartemen-jabodetabek-2024",
    topicId: "harga-jabodetabek",
    title: { id: "Perbandingan Harga Sewa Apartemen JABODETABEK 2024", en: "JABODETABEK Apartment Rental Price Comparison 2024" },
    excerpt: { id: "Analisis lengkap harga sewa apartemen di Jakarta, Bogor, Depok, Tangerang, dan Bekasi. Mana yang paling terjangkau?", en: "Complete analysis of apartment rental prices across JABODETABEK." },
    content: {
      id: `## Perbandingan Harga Sewa Apartemen JABODETABEK 2024\n\nMemilih kota tempat tinggal di Jabodetabek sangat bergantung pada budget dan gaya hidup Anda.\n\n## Jakarta\n- **Studio:** Rp 2,5 – 5 juta/bulan\n- **1BR:** Rp 4 – 9 juta/bulan\n- **2BR:** Rp 6 – 20 juta/bulan\n- Area premium (SCBD, Sudirman): bisa di atas Rp 15 juta/bulan\n\n## Tangerang Selatan (BSD, Bintaro)\n- **Studio:** Rp 2 – 4 juta/bulan\n- **1BR:** Rp 4 – 7 juta/bulan\n- **2BR:** Rp 6 – 12 juta/bulan\n\n## Bekasi (Summarecon, Galaxy)\n- **Studio:** Rp 2 – 3,5 juta/bulan\n- **1BR:** Rp 3,5 – 6 juta/bulan\n- **2BR:** Rp 5 – 9 juta/bulan\n\n## Depok (Margonda)\n- **Studio:** Rp 1,5 – 3 juta/bulan (paling cocok untuk mahasiswa)\n\n## Bogor\n- **Studio:** Rp 1,5 – 3 juta/bulan\n\n### Kesimpulan\nUntuk budget di bawah Rp 3 juta → Depok dan Bogor. Budget Rp 3-7 juta → Tangerang Selatan dan Bekasi. Di atas Rp 7 juta → Jakarta pusat/selatan. Temukan pilihan terlengkap di **SewaApartement.id**.`,
      en: `## JABODETABEK Apartment Price Comparison 2024\n\nJakarta: Studio from Rp 2.5M/month. BSD/Bintaro: Studio from Rp 2M/month. Bekasi: Studio from Rp 2M/month. Depok: Studio from Rp 1.5M/month (best for students). Find verified listings at SewaApartement.id.`,
    },
    category: { id: "Analisis Pasar", en: "Market Analysis" },
    tags: ["harga", "jabodetabek", "perbandingan", "2024"],
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
    author: "Tim Analis SewaApartement",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=60&q=80",
    publishedAt: "2024-02-20T08:00:00.000Z",
    readTime: 10,
    views: 3201,
    featured: false,
    autoGenerated: false,
  },
  {
    id: "seed-003",
    slug: "apartemen-terbaik-mahasiswa-depok-2024",
    topicId: "mahasiswa-depok",
    title: { id: "5 Apartemen Terbaik untuk Mahasiswa di Depok 2024", en: "5 Best Apartments for Students in Depok 2024" },
    excerpt: { id: "Rekomendasi apartemen terjangkau untuk mahasiswa UI, Gunadarma, dan kampus lainnya di Depok.", en: "Affordable apartment recommendations for students near major campuses in Depok." },
    content: {
      id: `## 5 Apartemen Terbaik untuk Mahasiswa di Depok 2024\n\nSebagai kota pelajar, Depok punya banyak pilihan apartemen dengan harga bersahabat.\n\n### 1. Margonda Residence 2, 3, 4, 5\nLokasinya paling strategis — terintegrasi dengan D'Mall Depok. Jarak 10 menit jalan kaki ke UI. Harga studio mulai **Rp 1,5 juta/bulan**.\n\n### 2. Atlanta Residences Depok\nDekat Universitas Indonesia dan Stasiun Depok Baru. Cocok untuk mahasiswa yang butuh akses KRL cepat ke Jakarta.\n\n### 3. De Papilio Tamansari\nApartemen modern dengan konsep green building. Harga terjangkau dan dekat kampus.\n\n### 4. Grand Depok City\nKawasan terintegrasi dengan mall. Cocok untuk mahasiswa yang ingin kenyamanan lengkap.\n\n### 5. Bogor Icon (untuk mahasiswa IPB)\nStrategis untuk mahasiswa IPB dengan pemandangan Gunung Salak.\n\n### Tips Memilih\n- Prioritaskan dekat transportasi publik (KRL/Angkot)\n- Pastikan WiFi sudah include\n- Cek apakah listrik dan air sudah include\n\nCari semua pilihan terbaik di **SewaApartement.id** — platform sewa apartemen JABODETABEK terlengkap.`,
      en: `## 5 Best Apartments for Students in Depok 2024\n\nMargonda Residence (from Rp 1.5M/month), Atlanta Residences, De Papilio, Grand Depok City, and Bogor Icon are top picks. Find them all at SewaApartement.id.`,
    },
    category: { id: "Rekomendasi", en: "Recommendation" },
    tags: ["mahasiswa", "depok", "UI", "murah"],
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    author: "Tim Redaksi SewaApartement",
    authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=60&q=80",
    publishedAt: "2024-02-10T08:00:00.000Z",
    readTime: 6,
    views: 2107,
    featured: false,
    autoGenerated: false,
  },
];

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const slug     = searchParams.get("slug");
  const featured = searchParams.get("featured");
  const limit    = searchParams.get("limit");
  const category = searchParams.get("category");

  let articles = [...SEED_BLOGS].sort(
    (a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
  );

  if (slug) {
    const post = articles.find((b) => b.slug === slug);
    if (!post) return NextResponse.json({ error: "Not found" }, { status: 404 });
    return NextResponse.json(post);
  }

  if (featured === "true") {
    articles = articles.filter((b) => b.featured);
  }

  if (category) {
    const cat = category.toLowerCase();
    articles = articles.filter(
      (b) =>
        b.category?.id?.toLowerCase().includes(cat) ||
        b.category?.en?.toLowerCase().includes(cat)
    );
  }

  if (limit) {
    articles = articles.slice(0, parseInt(limit));
  }

  return NextResponse.json(articles);
}
