"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Image from "next/image";
import Link from "next/link";
import { Calendar, Clock, ArrowRight, Tag, Search, Sparkles, RefreshCw, Rss } from "lucide-react";
import { useLanguage } from "@/hooks/useLanguage";
import { cn } from "@/lib/utils";

// Static seed articles (shown immediately, no fetch needed)
import { BLOG_POSTS } from "@/lib/data";

interface BlogPost {
  id: string;
  slug: string;
  title: { id: string; en: string };
  excerpt: { id: string; en: string };
  category: { id: string; en: string };
  image: string;
  author: string;
  authorAvatar?: string;
  publishedAt?: string;
  date?: string;
  readTime: number;
  views?: number;
  featured?: boolean;
  autoGenerated?: boolean;
}

const CATEGORIES = [
  { id: "all",        label: { id: "Semua",         en: "All" } },
  { id: "panduan",    label: { id: "Panduan",        en: "Guide" } },
  { id: "analisis",   label: { id: "Analisis Pasar", en: "Market Analysis" } },
  { id: "rekomendasi",label: { id: "Rekomendasi",    en: "Recommendation" } },
  { id: "tips",       label: { id: "Tips & Trik",    en: "Tips & Tricks" } },
  { id: "perbandingan",label:{ id: "Perbandingan",   en: "Comparison" } },
  { id: "investasi",  label: { id: "Investasi",      en: "Investment" } },
];

// Normalize articles from both sources (seed + API)
function normalize(raw: any): BlogPost {
  return {
    id:          raw.id,
    slug:        raw.slug,
    title:       raw.title,
    excerpt:     raw.excerpt,
    category:    raw.category,
    image:       raw.image,
    author:      raw.author,
    authorAvatar:raw.authorAvatar,
    publishedAt: raw.publishedAt ?? raw.date,
    date:        raw.date ?? raw.publishedAt,
    readTime:    raw.readTime,
    views:       raw.views ?? 0,
    featured:    raw.featured ?? false,
    autoGenerated: raw.autoGenerated ?? false,
  };
}

export default function BlogPage() {
  const { lang, t } = useLanguage();
  const [activeCategory, setActiveCategory] = useState("all");
  const [searchQuery, setSearchQuery]       = useState("");
  const [posts, setPosts]                   = useState<BlogPost[]>([]);
  const [loading, setLoading]               = useState(true);
  const [generating, setGenerating]         = useState(false);
  const [genMsg, setGenMsg]                 = useState("");

  // ── Load articles: API first, fall back to static seed ──────────────
  useEffect(() => {
    async function loadPosts() {
      setLoading(true);
      try {
        const res = await fetch("/api/blogs");
        if (res.ok) {
          const data = await res.json();
          if (Array.isArray(data) && data.length > 0) {
            // Merge server data + localStorage AI articles
            const localRaw = (() => {
              try { return JSON.parse(localStorage.getItem("sewa-ai-articles") ?? "[]"); } catch { return []; }
            })();
            const serverIds = new Set(data.map((p: any) => p.id));
            const localOnly = localRaw.filter((p: any) => !serverIds.has(p.id));
            const merged = [...data, ...localOnly].sort(
              (a: any, b: any) => new Date(b.publishedAt ?? b.date ?? "").getTime() - new Date(a.publishedAt ?? a.date ?? "").getTime()
            );
            setPosts(merged.map(normalize));
            return;
          }
        }
      } catch {/* network error — use seed */}
      // Fallback to static seed posts from data.ts
      setPosts(BLOG_POSTS.map(normalize));
      setLoading(false);
    }
    loadPosts().finally(() => setLoading(false));
  }, []);

  // ── Helpers: localStorage persistence untuk artikel AI ──────────────
  function loadLocalArticles(): BlogPost[] {
    try {
      const raw = localStorage.getItem("sewa-ai-articles");
      if (!raw) return [];
      return JSON.parse(raw);
    } catch { return []; }
  }
  function saveLocalArticle(article: BlogPost) {
    try {
      const existing = loadLocalArticles();
      if (!existing.find(a => a.id === article.id)) {
        existing.push(article);
        localStorage.setItem("sewa-ai-articles", JSON.stringify(existing));
      }
    } catch { /* ignore */ }
  }
  function mergeWithLocal(serverPosts: BlogPost[]): BlogPost[] {
    const local = loadLocalArticles();
    const serverIds = new Set(serverPosts.map(p => p.id));
    const localOnly = local.filter(p => !serverIds.has(p.id));
    return [...serverPosts, ...localOnly].sort(
      (a, b) => new Date(b.publishedAt ?? b.date ?? "").getTime() - new Date(a.publishedAt ?? a.date ?? "").getTime()
    );
  }

  // ── Manual trigger generate ───────────────────────────────────────────
  const handleManualGenerate = async () => {
    setGenerating(true);
    setGenMsg("");
    try {
      const res = await fetch("/api/generate-blog", {
        method: "POST",
        headers: { Authorization: "Bearer sewa-cron-secret-2024" },
      });
      const data = await res.json();

      if (data.success) {
        setGenMsg(data.message ?? "✅ Artikel baru berhasil dibuat!");
        // Simpan ke localStorage untuk persistence
        if (data.fullArticle) {
          saveLocalArticle(normalize(data.fullArticle));
        }
        // Reload posts dari API + merge dengan localStorage
        const newRes = await fetch("/api/blogs");
        if (newRes.ok) {
          const newData = await newRes.json();
          if (Array.isArray(newData)) {
            setPosts(mergeWithLocal(newData.map(normalize)));
          }
        } else {
          // Jika API gagal, refresh dari localStorage
          setPosts(prev => mergeWithLocal(prev));
        }
      } else {
        setGenMsg(data.message ?? data.error ?? "Gagal membuat artikel.");
      }
    } catch {
      setGenMsg("Error koneksi ke server.");
    }
    setGenerating(false);
  };

  // ── Filter ───────────────────────────────────────────────────────────
  const filtered = posts.filter(p => {
    const catMatch =
      activeCategory === "all" ||
      t(p.category).toLowerCase().includes(activeCategory.toLowerCase());
    const searchMatch =
      !searchQuery ||
      t(p.title).toLowerCase().includes(searchQuery.toLowerCase()) ||
      t(p.excerpt).toLowerCase().includes(searchQuery.toLowerCase());
    return catMatch && searchMatch;
  });

  const featured  = filtered.find(p => p.featured) ?? filtered[0];
  const restPosts = filtered.filter(p => p.id !== featured?.id);
  const autoCount = posts.filter(p => p.autoGenerated).length;

  return (
    <div className="page-dark pt-16 md:pt-20">
      {/* ── Hero ── */}
      <section className="relative py-16 px-4 sm:px-6 lg:px-8 overflow-hidden">
        <div className="absolute inset-0 grid-pattern opacity-10" />
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[500px] h-[200px] bg-primary-500/10 rounded-full blur-[80px]" />
        <div className="max-w-4xl mx-auto text-center relative">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary-600/20 border border-primary-500/30 text-primary-300 text-sm font-medium mb-4">
            <Rss size={14} className="text-accent-400" />
            {lang === "id" ? "Update otomatis setiap Senin" : "Auto-updated every Monday"}
            {autoCount > 0 && (
              <span className="ml-1 px-2 py-0.5 rounded-full bg-accent-500/20 text-accent-400 text-xs border border-accent-500/30">
                {autoCount} AI artikel
              </span>
            )}
          </motion.div>

          <motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}
            className="font-heading font-black text-white mb-3" style={{ fontSize: "clamp(2rem, 4vw, 3.5rem)" }}>
            Blog &amp; <span className="gradient-text">{lang === "id" ? "Artikel" : "Articles"}</span>
          </motion.h1>
          <motion.p initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
            className="text-white/60 mb-8">
            {lang === "id"
              ? "Tips, panduan, dan insight terbaru seputar dunia properti JABODETABEK."
              : "Tips, guides, and latest insights about JABODETABEK property world."}
          </motion.p>

          {/* Search */}
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}
            className="relative max-w-md mx-auto">
            <Search size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-white/40" />
            <input type="text" value={searchQuery} onChange={e => setSearchQuery(e.target.value)}
              placeholder={lang === "id" ? "Cari artikel..." : "Search articles..."}
              className="input-field pl-10" />
          </motion.div>
        </div>
      </section>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-20">

        {/* ── Admin: Manual Generate Button (dev/demo) ── */}
        <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
          <p className="text-white/40 text-sm">
            {loading ? "Memuat artikel..." : `${posts.length} ${lang === "id" ? "artikel tersedia" : "articles available"}`}
          </p>
          <button onClick={handleManualGenerate} disabled={generating}
            className={cn(
              "flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold border transition-all",
              generating
                ? "bg-white/5 border-white/10 text-white/30 cursor-not-allowed"
                : "bg-accent-600/20 border-accent-500/40 text-accent-300 hover:bg-accent-600/30"
            )}>
            {generating
              ? <><div className="w-3 h-3 border border-white/30 border-t-white/80 rounded-full animate-spin" /> {lang === "id" ? "Generating..." : "Generating..."}</>
              : <><Sparkles size={13} /> {lang === "id" ? "Generate Artikel Sekarang" : "Generate Article Now"}</>
            }
          </button>
        </div>

        {/* Generate status */}
        <AnimatePresence>
          {genMsg && (
            <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}
              className="mb-6 p-3 rounded-xl bg-accent-600/10 border border-accent-500/30 text-accent-300 text-sm flex items-center gap-2">
              <Sparkles size={14} /> {genMsg}
            </motion.div>
          )}
        </AnimatePresence>

        {/* ── Categories ── */}
        <div className="flex flex-wrap gap-2 mb-10">
          {CATEGORIES.map(cat => (
            <button key={cat.id} onClick={() => setActiveCategory(cat.id)}
              className={cn(
                "px-4 py-2 rounded-xl text-sm font-medium border transition-all duration-200",
                activeCategory === cat.id
                  ? "bg-primary-600 border-primary-500 text-white shadow-glow-blue"
                  : "bg-white/5 border-white/10 text-white/60 hover:text-white hover:bg-white/10"
              )}>
              {t(cat.label)}
            </button>
          ))}
        </div>

        {/* ── Loading skeleton ── */}
        {loading && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[...Array(6)].map((_, i) => (
              <div key={i} className="glass rounded-2xl overflow-hidden">
                <div className="skeleton aspect-video w-full" />
                <div className="p-5 space-y-3">
                  <div className="skeleton h-4 w-1/3 rounded" />
                  <div className="skeleton h-5 w-full rounded" />
                  <div className="skeleton h-4 w-4/5 rounded" />
                </div>
              </div>
            ))}
          </div>
        )}

        {/* ── Featured post ── */}
        {!loading && featured && activeCategory === "all" && !searchQuery && (
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-12">
            <Link href={`/blog/${featured.slug}`} className="group block">
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-0 glass rounded-3xl overflow-hidden hover:border-primary-500/30 transition-all duration-300">
                <div className="relative aspect-video lg:aspect-auto lg:h-80">
                  <Image src={featured.image} alt={t(featured.title)} fill
                    className="object-cover group-hover:scale-105 transition-transform duration-700"
                    sizes="(max-width: 1024px) 100vw, 50vw" />
                  <div className="absolute inset-0 bg-gradient-to-r from-dark-900/40 to-transparent lg:bg-none" />
                  {featured.autoGenerated && (
                    <div className="absolute top-3 left-3 flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-accent-500/80 backdrop-blur-sm text-white text-xs font-semibold">
                      <Sparkles size={10} /> AI Generated
                    </div>
                  )}
                </div>
                <div className="p-8 flex flex-col justify-center">
                  <div className="flex items-center gap-2 mb-4">
                    <span className="badge bg-accent-500/20 text-accent-400 border border-accent-500/30 text-xs">
                      ⭐ {lang === "id" ? "Artikel Unggulan" : "Featured Article"}
                    </span>
                    <span className="text-white/40 text-xs">{t(featured.category)}</span>
                  </div>
                  <h2 className="font-heading font-bold text-white text-xl md:text-2xl mb-3 group-hover:text-primary-300 transition-colors leading-snug">
                    {t(featured.title)}
                  </h2>
                  <p className="text-white/60 text-sm leading-relaxed mb-6">{t(featured.excerpt)}</p>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3 text-white/40 text-xs">
                      <span>{featured.author}</span>
                      <span>•</span>
                      <div className="flex items-center gap-1">
                        <Calendar size={11} />
                        {new Date(featured.publishedAt ?? featured.date ?? "").toLocaleDateString(
                          lang === "id" ? "id-ID" : "en-US",
                          { year: "numeric", month: "short", day: "numeric" }
                        )}
                      </div>
                      <div className="flex items-center gap-1"><Clock size={11} />{featured.readTime} min</div>
                    </div>
                    <span className="flex items-center gap-1.5 text-primary-400 text-sm font-semibold group-hover:gap-2 transition-all">
                      {lang === "id" ? "Baca" : "Read"} <ArrowRight size={14} />
                    </span>
                  </div>
                </div>
              </div>
            </Link>
          </motion.div>
        )}

        {/* ── Posts grid ── */}
        {!loading && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {(activeCategory === "all" && !searchQuery ? restPosts : filtered).map((post, i) => (
              <motion.div key={post.id}
                initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.06 }} whileHover={{ y: -5 }}>
                <Link href={`/blog/${post.slug}`} className="group block h-full">
                  <div className="glass rounded-2xl overflow-hidden hover:border-primary-500/20 transition-all duration-300 h-full flex flex-col">
                    <div className="relative aspect-video overflow-hidden">
                      <Image src={post.image} alt={t(post.title)} fill
                        className="object-cover group-hover:scale-110 transition-transform duration-700"
                        sizes="(max-width: 768px) 100vw, 33vw" />
                      <div className="absolute top-3 left-3 flex gap-1.5">
                        <span className="badge bg-dark-900/80 backdrop-blur-sm text-white/70 border-white/10 text-xs">
                          <Tag size={9} /> {t(post.category)}
                        </span>
                        {post.autoGenerated && (
                          <span className="badge bg-accent-500/70 backdrop-blur-sm text-white text-xs">
                            <Sparkles size={9} /> AI
                          </span>
                        )}
                      </div>
                    </div>
                    <div className="p-5 flex-1 flex flex-col">
                      <h3 className="font-heading font-bold text-white text-sm md:text-base leading-snug mb-2 group-hover:text-primary-300 transition-colors line-clamp-2 flex-1">
                        {t(post.title)}
                      </h3>
                      <p className="text-white/50 text-xs leading-relaxed mb-4 line-clamp-2">{t(post.excerpt)}</p>
                      <div className="flex items-center justify-between text-white/30 text-xs mt-auto pt-3 border-t border-white/5">
                        <div className="flex items-center gap-2">
                          <span className="truncate max-w-[100px]">{post.author}</span>
                          <span>•</span>
                          <div className="flex items-center gap-1"><Clock size={10} />{post.readTime} min</div>
                          {(post.views ?? 0) > 0 && (
                            <><span>•</span><span>{post.views} views</span></>
                          )}
                        </div>
                        <div className="flex items-center gap-1 text-primary-400 text-xs font-medium opacity-0 group-hover:opacity-100 transition-opacity">
                          {lang === "id" ? "Baca" : "Read"} <ArrowRight size={11} />
                        </div>
                      </div>
                    </div>
                  </div>
                </Link>
              </motion.div>
            ))}
          </div>
        )}

        {/* ── Empty state ── */}
        {!loading && filtered.length === 0 && (
          <div className="text-center py-20">
            <div className="text-5xl mb-4">📝</div>
            <h3 className="text-white font-bold text-xl mb-2">
              {lang === "id" ? "Tidak ada artikel ditemukan" : "No articles found"}
            </h3>
            <button onClick={() => { setActiveCategory("all"); setSearchQuery(""); }} className="btn-primary mt-4">
              {lang === "id" ? "Reset Filter" : "Reset Filter"}
            </button>
          </div>
        )}

        {/* ── Auto-update info banner ── */}
        <motion.div initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }}
          className="mt-16 p-6 glass rounded-2xl border border-primary-500/20 flex flex-col sm:flex-row items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-primary-600/20 border border-primary-500/30 flex items-center justify-center flex-shrink-0">
            <Rss className="text-primary-400" size={22} />
          </div>
          <div className="flex-1 text-center sm:text-left">
            <h3 className="font-bold text-white mb-1">
              {lang === "id" ? "Blog Diperbarui Otomatis Setiap Senin" : "Blog Auto-Updated Every Monday"}
            </h3>
            <p className="text-white/50 text-sm">
              {lang === "id"
                ? "Sistem kami menggunakan AI untuk generate artikel properti terbaru setiap minggu. Topik mencakup tips sewa, analisis pasar, rekomendasi, dan banyak lagi."
                : "Our system uses AI to generate the latest property articles every week. Topics include rental tips, market analysis, recommendations, and more."}
            </p>
          </div>
          <div className="text-white/30 text-xs text-center sm:text-right flex-shrink-0">
            <div className="flex items-center gap-1.5 justify-center sm:justify-end mb-1">
              <span className="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
              <span className="text-green-400">{lang === "id" ? "Aktif" : "Active"}</span>
            </div>
            <div>{lang === "id" ? "Jadwal: Senin 08:00 WIB" : "Schedule: Monday 08:00 WIB"}</div>
            <div>{lang === "id" ? "8 topik berrotasi" : "8 rotating topics"}</div>
          </div>
        </motion.div>

      </div>
    </div>
  );
}
